using System.Data.Common;

namespace Drizzle4Dotnet.Cli.Services;

/// <summary>
/// CLI-specific migration manager that tracks applied migrations in a database table
/// with status (running/success/failed) and execution logs.
/// Matches migrations by their sequential MigrationId (e.g., "0001") rather than name,
/// so auto-generated random names don't affect which migrations are considered applied.
/// Schema and table names are configurable.
/// </summary>
public class MigrationManager
{
    private readonly DbConnection _connection;
    private readonly DbTransaction? _transaction;
    private readonly string _schemaName;
    private readonly string _tableName;

    /// <summary>
    /// Creates a new MigrationManager for the given connection
    /// with custom migration tracking table schema/name.
    /// </summary>
    public MigrationManager(
        DbConnection connection,
        DbTransaction? transaction = null,
        string schemaName = "public",
        string tableName = "__Migrations")
    {
        _connection = connection;
        _transaction = transaction;
        _schemaName = schemaName;
        _tableName = tableName;
    }

    /// <summary>
    /// Ensures the migration history table exists in the database.
    /// Schema:
    ///   Id           BIGINT (PK, auto-increment)
    ///   MigrationId  TEXT NOT NULL       — the journal's IncrementalId (e.g., "0001")
    ///   Name         TEXT NOT NULL       — human-readable migration name
    ///   AppliedAt    TIMESTAMP DEFAULT NOW()
    ///   Checksum     TEXT NOT NULL
    ///   Status       TEXT NOT NULL DEFAULT 'running'  (running/success/failed)
    ///   Log          TEXT (nullable, stores error details)
    /// </summary>
    public async Task EnsureMigrationTableAsync()
    {
        var createTableSql = $@"
CREATE TABLE IF NOT EXISTS {_schemaName}.{_tableName} (
    ""Id"" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""MigrationId"" TEXT NOT NULL,
    ""Name"" TEXT NOT NULL,
    ""AppliedAt"" TIMESTAMP NOT NULL DEFAULT NOW(),
    ""Checksum"" TEXT NOT NULL,
    ""Status"" TEXT NOT NULL DEFAULT 'running',
    ""Log"" TEXT
)";

        await using var cmd = _connection.CreateCommand();
        cmd.Transaction = _transaction;
        cmd.CommandText = createTableSql;
        await cmd.ExecuteNonQueryAsync();
    }

    /// <summary>
    /// Gets a list of successfully applied migrations from the database, ordered by Id.
    /// Only returns records with Status = 'success' so failed/running ones are re-attempted.
    /// </summary>
    public async Task<List<AppliedMigration>> GetAppliedMigrationsAsync()
    {
        await EnsureMigrationTableAsync();

        var result = new List<AppliedMigration>();
        await using var cmd = _connection.CreateCommand();
        cmd.Transaction = _transaction;
        cmd.CommandText = $@"SELECT ""Id"", ""MigrationId"", ""Name"", ""AppliedAt"", ""Checksum"", ""Status"", ""Log"" FROM {_schemaName}.{_tableName} WHERE ""Status"" = 'success' ORDER BY ""Id"" ASC";
        await using var reader = await cmd.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            result.Add(new AppliedMigration(
                reader.GetInt64(0),
                reader.GetString(1),
                reader.GetString(2),
                reader.GetDateTime(3),
                reader.GetString(4),
                reader.GetString(5),
                reader.IsDBNull(6) ? null : reader.GetString(6)
            ));
        }
        return result;
    }

    /// <summary>
    /// Gets migration records by MigrationId regardless of status.
    /// Used for failure recovery to check if a "running" record exists.
    /// </summary>
    public async Task<List<AppliedMigration>> GetMigrationsByMigrationIdAsync(string migrationId)
    {
        await EnsureMigrationTableAsync();

        var result = new List<AppliedMigration>();
        await using var cmd = _connection.CreateCommand();
        cmd.Transaction = _transaction;
        cmd.CommandText = $@"SELECT ""Id"", ""MigrationId"", ""Name"", ""AppliedAt"", ""Checksum"", ""Status"", ""Log"" FROM {_schemaName}.{_tableName} WHERE ""MigrationId"" = @migrationId ORDER BY ""Id"" DESC";

        var idParam = cmd.CreateParameter();
        idParam.ParameterName = "migrationId";
        idParam.Value = migrationId;
        cmd.Parameters.Add(idParam);

        await using var reader = await cmd.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            result.Add(new AppliedMigration(
                reader.GetInt64(0),
                reader.GetString(1),
                reader.GetString(2),
                reader.GetDateTime(3),
                reader.GetString(4),
                reader.GetString(5),
                reader.IsDBNull(6) ? null : reader.GetString(6)
            ));
        }
        return result;
    }

    /// <summary>
    /// Inserts a "running" migration record before execution.
    /// Returns the auto-generated Id of the new record.
    /// </summary>
    public async Task<long> StartMigrationAsync(string migrationId, string name, string checksum)
    {
        await EnsureMigrationTableAsync();

        await using var cmd = _connection.CreateCommand();
        cmd.Transaction = _transaction;

        cmd.CommandText = $@"
INSERT INTO {_schemaName}.{_tableName} (""MigrationId"", ""Name"", ""Checksum"", ""Status"")
VALUES (@migrationId, @name, @checksum, 'running')
RETURNING ""Id""";

        var midParam = cmd.CreateParameter();
        midParam.ParameterName = "migrationId";
        midParam.Value = migrationId;
        cmd.Parameters.Add(midParam);

        var nameParam = cmd.CreateParameter();
        nameParam.ParameterName = "name";
        nameParam.Value = name;
        cmd.Parameters.Add(nameParam);

        var checksumParam = cmd.CreateParameter();
        checksumParam.ParameterName = "checksum";
        checksumParam.Value = checksum;
        cmd.Parameters.Add(checksumParam);

        var result = await cmd.ExecuteScalarAsync();
        return Convert.ToInt64(result);
    }

    /// <summary>
    /// Updates a migration record after execution with final status and optional log.
    /// </summary>
    public async Task CompleteMigrationAsync(long id, string status, string? log = null)
    {
        await using var cmd = _connection.CreateCommand();
        cmd.Transaction = _transaction;

        if (log != null)
        {
            cmd.CommandText = $@"
UPDATE {_schemaName}.{_tableName}
SET ""Status"" = @status, ""Log"" = @log
WHERE ""Id"" = @id";
        }
        else
        {
            cmd.CommandText = $@"
UPDATE {_schemaName}.{_tableName}
SET ""Status"" = @status
WHERE ""Id"" = @id";
        }

        var statusParam = cmd.CreateParameter();
        statusParam.ParameterName = "status";
        statusParam.Value = status;
        cmd.Parameters.Add(statusParam);

        if (log != null)
        {
            var logParam = cmd.CreateParameter();
            logParam.ParameterName = "log";
            logParam.Value = log;
            cmd.Parameters.Add(logParam);
        }

        var idParam = cmd.CreateParameter();
        idParam.ParameterName = "id";
        idParam.Value = id;
        cmd.Parameters.Add(idParam);

        await cmd.ExecuteNonQueryAsync();
    }
}

/// <summary>
/// Represents a tracked migration record from the database.
/// </summary>
public readonly struct AppliedMigration
{
    public long Id { get; }
    public string MigrationId { get; }
    public string Name { get; }
    public DateTime AppliedAt { get; }
    public string Checksum { get; }
    public string Status { get; }
    public string? Log { get; }

    public AppliedMigration(long id, string migrationId, string name, DateTime appliedAt, string checksum, string status, string? log = null)
    {
        Id = id;
        MigrationId = migrationId;
        Name = name;
        AppliedAt = appliedAt;
        Checksum = checksum;
        Status = status;
        Log = log;
    }
}
