using System.Data.Common;

namespace Drizzle4Dotnet.Cli.Services;

/// <summary>
/// CLI-specific migration manager that tracks applied migrations in a database table.
/// Migrations are recorded only after successful execution (no "running" status).
/// Schema and table names are configurable.
/// </summary>
public class MigrationManager
{
    private readonly DbConnection _connection;
    private readonly DbTransaction? _transaction;
    private readonly string _schemaName;
    private readonly string _tableName;

    /// <summary>
    /// Creates a new MigrationManager for the given connection
    /// with custom migration tracking table schema/name.
    /// </summary>
    public MigrationManager(
        DbConnection connection,
        DbTransaction? transaction = null,
        string schemaName = "public",
        string tableName = "__Migrations")
    {
        _connection = connection;
        _transaction = transaction;
        _schemaName = schemaName;
        _tableName = tableName;
    }

    /// <summary>
    /// Ensures the migration history table exists in the database.
    /// Schema:
    ///   Id           BIGINT (PK, auto-increment)
    ///   MigrationId  TEXT NOT NULL       — the journal's IncrementalId (e.g., "0001")
    ///   Name         TEXT NOT NULL       — human-readable migration name
    ///   AppliedAt    TIMESTAMP DEFAULT NOW()
    ///   Checksum     TEXT NOT NULL
    /// </summary>
    public async Task EnsureMigrationTableAsync()
    {
        var createTableSql = $@"
CREATE TABLE IF NOT EXISTS {_schemaName}.{_tableName} (
    ""Id"" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""MigrationId"" TEXT NOT NULL,
    ""Name"" TEXT NOT NULL,
    ""AppliedAt"" TIMESTAMP NOT NULL DEFAULT NOW(),
    ""Checksum"" TEXT NOT NULL
)";

        await using var cmd = _connection.CreateCommand();
        cmd.Transaction = _transaction;
        cmd.CommandText = createTableSql;
        await cmd.ExecuteNonQueryAsync();
    }

    /// <summary>
    /// Gets a list of applied migrations from the database, ordered by Id.
    /// </summary>
    public async Task<List<AppliedMigration>> GetAppliedMigrationsAsync()
    {
        await EnsureMigrationTableAsync();

        var result = new List<AppliedMigration>();
        await using var cmd = _connection.CreateCommand();
        cmd.Transaction = _transaction;
        cmd.CommandText = $@"SELECT ""Id"", ""MigrationId"", ""Name"", ""AppliedAt"", ""Checksum"" FROM {_schemaName}.{_tableName} ORDER BY ""Id"" ASC";
        await using var reader = await cmd.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            result.Add(new AppliedMigration(
                reader.GetInt64(0),
                reader.GetString(1),
                reader.GetString(2),
                reader.GetDateTime(3),
                reader.GetString(4)
            ));
        }
        return result;
    }

    /// <summary>
    /// Inserts a migration record after successful execution.
    /// </summary>
    public async Task<long> InsertMigrationAsync(string migrationId, string name, string checksum)
    {
        await EnsureMigrationTableAsync();

        await using var cmd = _connection.CreateCommand();
        cmd.Transaction = _transaction;

        cmd.CommandText = $@"
INSERT INTO {_schemaName}.{_tableName} (""MigrationId"", ""Name"", ""Checksum"")
VALUES (@migrationId, @name, @checksum)
RETURNING ""Id""";

        var midParam = cmd.CreateParameter();
        midParam.ParameterName = "migrationId";
        midParam.Value = migrationId;
        cmd.Parameters.Add(midParam);

        var nameParam = cmd.CreateParameter();
        nameParam.ParameterName = "name";
        nameParam.Value = name;
        cmd.Parameters.Add(nameParam);

        var checksumParam = cmd.CreateParameter();
        checksumParam.ParameterName = "checksum";
        checksumParam.Value = checksum;
        cmd.Parameters.Add(checksumParam);

        var result = await cmd.ExecuteScalarAsync();
        return Convert.ToInt64(result);
    }
}

/// <summary>
/// Represents a tracked migration record from the database.
/// </summary>
public readonly struct AppliedMigration
{
    public long Id { get; }
    public string MigrationId { get; }
    public string Name { get; }
    public DateTime AppliedAt { get; }
    public string Checksum { get; }

    public AppliedMigration(long id, string migrationId, string name, DateTime appliedAt, string checksum)
    {
        Id = id;
        MigrationId = migrationId;
        Name = name;
        AppliedAt = appliedAt;
        Checksum = checksum;
    }
}
