// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Data.Common;
using Drizzle4Dotnet.Core.Schema.Columns;
using System.Data.Common;
using Drizzle4Dotnet.Core.Query.Delete;
using Drizzle4Dotnet.Core.Query.Insert;
using Drizzle4Dotnet.Core.Query.Select;
using Drizzle4Dotnet.Core.Query.Update;
using Drizzle4Dotnet.Core.Schema.Columns;
using Drizzle4Dotnet.Core.Schema.Tables;
using Drizzle4Dotnet.Core.Shared;
namespace Drizzle4Dotnet.Core;

public static class QueryBuilderExtensions
{
    public static SelectQuery<T1, TDialect> Select<T1, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, TDialect>(col1));

    public static SelectQuery<T1, TDialect> SelectDistinct<T1, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, TDialect>(col1));

    public static SelectQuery<(T1, T2), TDialect> Select<T1, T2, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, TDialect>(col1, col2));

    public static SelectQuery<(T1, T2), TDialect> SelectDistinct<T1, T2, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, TDialect>(col1, col2));

    public static SelectQuery<(T1, T2, T3), TDialect> Select<T1, T2, T3, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, TDialect>(col1, col2, col3));

    public static SelectQuery<(T1, T2, T3), TDialect> SelectDistinct<T1, T2, T3, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, TDialect>(col1, col2, col3));

    public static SelectQuery<(T1, T2, T3, T4), TDialect> Select<T1, T2, T3, T4, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, TDialect>(col1, col2, col3, col4));

    public static SelectQuery<(T1, T2, T3, T4), TDialect> SelectDistinct<T1, T2, T3, T4, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, TDialect>(col1, col2, col3, col4));

    public static SelectQuery<(T1, T2, T3, T4, T5), TDialect> Select<T1, T2, T3, T4, T5, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4, ISql<T5> col5) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, TDialect>(col1, col2, col3, col4, col5));

    public static SelectQuery<(T1, T2, T3, T4, T5), TDialect> SelectDistinct<T1, T2, T3, T4, T5, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4, ISql<T5> col5) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, TDialect>(col1, col2, col3, col4, col5));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6), TDialect> Select<T1, T2, T3, T4, T5, T6, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4, ISql<T5> col5, ISql<T6> col6) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, TDialect>(col1, col2, col3, col4, col5, col6));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6), TDialect> SelectDistinct<T1, T2, T3, T4, T5, T6, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4, ISql<T5> col5, ISql<T6> col6) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, TDialect>(col1, col2, col3, col4, col5, col6));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7), TDialect> Select<T1, T2, T3, T4, T5, T6, T7, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4, ISql<T5> col5, ISql<T6> col6, ISql<T7> col7) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, TDialect>(col1, col2, col3, col4, col5, col6, col7));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7), TDialect> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4, ISql<T5> col5, ISql<T6> col6, ISql<T7> col7) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, TDialect>(col1, col2, col3, col4, col5, col6, col7));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8), TDialect> Select<T1, T2, T3, T4, T5, T6, T7, T8, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4, ISql<T5> col5, ISql<T6> col6, ISql<T7> col7, ISql<T8> col8) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8), TDialect> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4, ISql<T5> col5, ISql<T6> col6, ISql<T7> col7, ISql<T8> col8) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9), TDialect> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4, ISql<T5> col5, ISql<T6> col6, ISql<T7> col7, ISql<T8> col8, ISql<T9> col9) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9), TDialect> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4, ISql<T5> col5, ISql<T6> col6, ISql<T7> col7, ISql<T8> col8, ISql<T9> col9) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10), TDialect> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4, ISql<T5> col5, ISql<T6> col6, ISql<T7> col7, ISql<T8> col8, ISql<T9> col9, ISql<T10> col10) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10), TDialect> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4, ISql<T5> col5, ISql<T6> col6, ISql<T7> col7, ISql<T8> col8, ISql<T9> col9, ISql<T10> col10) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11), TDialect> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4, ISql<T5> col5, ISql<T6> col6, ISql<T7> col7, ISql<T8> col8, ISql<T9> col9, ISql<T10> col10, ISql<T11> col11) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11), TDialect> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4, ISql<T5> col5, ISql<T6> col6, ISql<T7> col7, ISql<T8> col8, ISql<T9> col9, ISql<T10> col10, ISql<T11> col11) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12), TDialect> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4, ISql<T5> col5, ISql<T6> col6, ISql<T7> col7, ISql<T8> col8, ISql<T9> col9, ISql<T10> col10, ISql<T11> col11, ISql<T12> col12) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12), TDialect> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4, ISql<T5> col5, ISql<T6> col6, ISql<T7> col7, ISql<T8> col8, ISql<T9> col9, ISql<T10> col10, ISql<T11> col11, ISql<T12> col12) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13), TDialect> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4, ISql<T5> col5, ISql<T6> col6, ISql<T7> col7, ISql<T8> col8, ISql<T9> col9, ISql<T10> col10, ISql<T11> col11, ISql<T12> col12, ISql<T13> col13) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13), TDialect> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4, ISql<T5> col5, ISql<T6> col6, ISql<T7> col7, ISql<T8> col8, ISql<T9> col9, ISql<T10> col10, ISql<T11> col11, ISql<T12> col12, ISql<T13> col13) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14), TDialect> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4, ISql<T5> col5, ISql<T6> col6, ISql<T7> col7, ISql<T8> col8, ISql<T9> col9, ISql<T10> col10, ISql<T11> col11, ISql<T12> col12, ISql<T13> col13, ISql<T14> col14) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14), TDialect> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4, ISql<T5> col5, ISql<T6> col6, ISql<T7> col7, ISql<T8> col8, ISql<T9> col9, ISql<T10> col10, ISql<T11> col11, ISql<T12> col12, ISql<T13> col13, ISql<T14> col14) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15), TDialect> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4, ISql<T5> col5, ISql<T6> col6, ISql<T7> col7, ISql<T8> col8, ISql<T9> col9, ISql<T10> col10, ISql<T11> col11, ISql<T12> col12, ISql<T13> col13, ISql<T14> col14, ISql<T15> col15) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14, col15));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15), TDialect> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4, ISql<T5> col5, ISql<T6> col6, ISql<T7> col7, ISql<T8> col8, ISql<T9> col9, ISql<T10> col10, ISql<T11> col11, ISql<T12> col12, ISql<T13> col13, ISql<T14> col14, ISql<T15> col15) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14, col15));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16), TDialect> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4, ISql<T5> col5, ISql<T6> col6, ISql<T7> col7, ISql<T8> col8, ISql<T9> col9, ISql<T10> col10, ISql<T11> col11, ISql<T12> col12, ISql<T13> col13, ISql<T14> col14, ISql<T15> col15, ISql<T16> col16) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14, col15, col16));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16), TDialect> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TDialect>(this IQueryBuilder<TDialect> builder, ISql<T1> col1, ISql<T2> col2, ISql<T3> col3, ISql<T4> col4, ISql<T5> col5, ISql<T6> col6, ISql<T7> col7, ISql<T8> col8, ISql<T9> col9, ISql<T10> col10, ISql<T11> col11, ISql<T12> col12, ISql<T13> col13, ISql<T14> col14, ISql<T15> col15, ISql<T16> col16) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14, col15, col16));
}
