// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Data.Common;
using Drizzle4Dotnet.Core.Schema.Columns;
using System.Data.Common;
using Drizzle4Dotnet.Core.Query.Delete;
using Drizzle4Dotnet.Core.Query.Insert;
using Drizzle4Dotnet.Core.Query.Select;
using Drizzle4Dotnet.Core.Query.Update;
using Drizzle4Dotnet.Core.Schema.Columns;
using Drizzle4Dotnet.Core.Schema.Tables;
using Drizzle4Dotnet.Core.Shared;
namespace Drizzle4Dotnet.Core;

public static class QueryBuilderExtensions
{
    public static SelectQuery<T1, TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> Select<T1, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, TDialect>(col1));

    public static SelectQuery<T1, TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> SelectDistinct<T1, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, TDialect>(col1));

    public static SelectQuery<(T1, T2), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> Select<T1, T2, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, TDialect>(col1, col2));

    public static SelectQuery<(T1, T2), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> SelectDistinct<T1, T2, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, TDialect>(col1, col2));

    public static SelectQuery<(T1, T2, T3), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> Select<T1, T2, T3, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, TDialect>(col1, col2, col3));

    public static SelectQuery<(T1, T2, T3), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> SelectDistinct<T1, T2, T3, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, TDialect>(col1, col2, col3));

    public static SelectQuery<(T1, T2, T3, T4), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> Select<T1, T2, T3, T4, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, TDialect>(col1, col2, col3, col4));

    public static SelectQuery<(T1, T2, T3, T4), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> SelectDistinct<T1, T2, T3, T4, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, TDialect>(col1, col2, col3, col4));

    public static SelectQuery<(T1, T2, T3, T4, T5), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> Select<T1, T2, T3, T4, T5, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, TDialect>(col1, col2, col3, col4, col5));

    public static SelectQuery<(T1, T2, T3, T4, T5), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> SelectDistinct<T1, T2, T3, T4, T5, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, TDialect>(col1, col2, col3, col4, col5));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> Select<T1, T2, T3, T4, T5, T6, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, TDialect>(col1, col2, col3, col4, col5, col6));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> SelectDistinct<T1, T2, T3, T4, T5, T6, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, TDialect>(col1, col2, col3, col4, col5, col6));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> Select<T1, T2, T3, T4, T5, T6, T7, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, TDialect>(col1, col2, col3, col4, col5, col6, col7));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, TDialect>(col1, col2, col3, col4, col5, col6, col7));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> Select<T1, T2, T3, T4, T5, T6, T7, T8, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13, IAliasedSql<T14> col14) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13, IAliasedSql<T14> col14) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13, IAliasedSql<T14> col14, IAliasedSql<T15> col15) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14, col15));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13, IAliasedSql<T14> col14, IAliasedSql<T15> col15) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14, col15));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13, IAliasedSql<T14> col14, IAliasedSql<T15> col15, IAliasedSql<T16> col16) where TDialect : ISqlDialect
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14, col15, col16));

    public static SelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16), TDialect, TypedTupleGeneratedSubqueryTable<TDialect>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TDialect>(this IQueryBuilder<TDialect> builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13, IAliasedSql<T14> col14, IAliasedSql<T15> col15, IAliasedSql<T16> col16) where TDialect : ISqlDialect
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TDialect>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14, col15, col16));
}
