using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SourceGenerators;

[Generator]
public class DbSelectGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => GetClassModel(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(classDeclarations.Collect(), GenerateCode);
        context.RegisterPostInitializationOutput(i => {
            var source1 = GenerateSource1();
            i.AddSource("TypedTupleSelectedColumns.g.cs", SourceText.From(source1, Encoding.UTF8));
            // var source2 = GenerateSource2();
            // i.AddSource("QueryBuilderExtensions.g.cs", SourceText.From(source2, Encoding.UTF8));
        });
    }

//     public string GenerateSource2()
//     {
//         var sb = new StringBuilder();
//         sb.AppendLine("// <auto-generated/>");
//         sb.AppendLine("using System;");
//         sb.AppendLine("using System.Collections.Generic;");
//         sb.AppendLine("using System.Data.Common;");
//         sb.AppendLine("using Drizzle4Dotnet.Core.Schema.Columns;");
//         sb.AppendLine($@"using System.Data.Common;
// using Drizzle4Dotnet.Core.Query.Delete;
// using Drizzle4Dotnet.Core.Query.Insert;
// using Drizzle4Dotnet.Core.Query.Select;
// using Drizzle4Dotnet.Core.Query.Update;
// using Drizzle4Dotnet.Core.Schema.Columns;
// using Drizzle4Dotnet.Core.Schema.Tables;
// using Drizzle4Dotnet.Core.Shared;");
//         sb.AppendLine("namespace Drizzle4Dotnet.Core;");
//         sb.AppendLine("\npublic static class QueryBuilderExtensions\n{");
//         for (int i = 1; i <= 16; i++)
//         {
//             var range = Enumerable.Range(1, i).ToList();
//             var tTypes = string.Join(", ", range.Select(n => $"T{n}"));
//             var colParams = string.Join(", ", range.Select(n => $"IAliasedSql<T{n}> col{n}"));
//             var colArgs = string.Join(", ", range.Select(n => $"col{n}"));
//             string returnType = i == 1 ? "T1" : $"({tTypes})";
//
//             sb.AppendLine($@"
//     public static SelectQuery<{returnType}, TDialect, TypedTupleGeneratedSubqueryTable<{returnType}, TDialect>> Select<{tTypes}, TDialect>(this IQueryBuilder<TDialect> builder, {colParams}) where TDialect : ISqlDialect
//         => builder.Select(new TypedTupleSelectedColumns<{tTypes}, TDialect>({colArgs}));
//
//     public static SelectQuery<{returnType}, TDialect, TypedTupleGeneratedSubqueryTable<{returnType}, TDialect>> SelectDistinct<{tTypes}, TDialect>(this IQueryBuilder<TDialect> builder, {colParams}) where TDialect : ISqlDialect
//         => builder.SelectDistinct(new TypedTupleSelectedColumns<{tTypes}, TDialect>({colArgs}));");
//         }
//         sb.AppendLine("}");
//         return sb.ToString();
//     }
    
    public string GenerateSource1()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Data.Common;");
        sb.AppendLine("using Drizzle4Dotnet.Core.Schema.Columns;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine("namespace Drizzle4Dotnet.Core.Shared;");

        for (int i = 1; i <= 16; i++)
        {
            var range = Enumerable.Range(1, i).ToList();
            var tParams = string.Join(", ", range.Select(n => $"T{n}"));
            string interfaceType = i == 1 ? "T1" : $"({tParams})";
            var fields = string.Join("\n    ", range.Select(n => $"private readonly IAliasedSql<T{n}> _col{n};"));
            var ctorParams = string.Join(", ", range.Select(n => $"IAliasedSql<T{n}> col{n}"));
            var ctorAssigns = string.Join("\n        ", range.Select(n => $"_col{n} = col{n};"));
            var mapperParts = string.Join(",\n            ",
                range.Select(n => $"r.IsDBNull({n - 1}) ? default! : r.GetFieldValue<T{n}>({n - 1})"));
            var builderInvocations = string.Join("\n        sqlBuilder.Append(\", \");\n        ",
                range.Select(n => $"_col{n}.BuildSql(sqlBuilder);"));

            sb.AppendLine($@"
public class TypedTupleSelectedColumns<{tParams}, TDialect> : ITypedTupleSelectedColumns<{interfaceType}, TDialect, TypedTupleGeneratedSubqueryTable<{interfaceType}, TDialect>> 
    where TDialect : ISqlDialect
{{
    {fields}
    
    public TypedTupleSelectedColumns({ctorParams})
    {{
        {ctorAssigns}
    }}

    public void BuildSql(ISqlBuilder sqlBuilder)
    {{
        {builderInvocations}
    }}


    public {interfaceType} Mapper(DbDataReader r)
    {{
        return (
            {mapperParts}
        );
    }}

    IAliasedSql<T> Field<T>(IAliasedSql<T> column) {{
{string.Join("\n        ", range.Select(n => $@"        if (column.Identifier == _col{n}.Identifier)
        {{
            return _col{n} as IAliasedSql<T>;
        }}"))}
        throw new ArgumentException($""""Column '{{{{columnName}}}}' not found in selection."""");
    }}
    public IAliasedSql<T> Field<T>(string columnName)
    {{
{string.Join("\n", range.Select(n => $@"        if (columnName == _col{n}.Identifier)
        {{
            return _col{n} as IAliasedSql<T>;
        }}"))}
        throw new ArgumentException($""Column '{{columnName}}' not found in selection."");
    }}
}}");
        }
        return sb.ToString();
    }
    
    private void GenerateCode(SourceProductionContext context, ImmutableArray<ClassModel?> classes)
    {
        if (classes.IsDefaultOrEmpty) return;

        foreach (var model in classes.Distinct())
        {
            if (model == null) continue;
            
            var sb = new StringBuilder();
            
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Data.Common;");
            sb.AppendLine("using Drizzle4Dotnet.Core.Shared;");
            sb.AppendLine("using System.Text;");
            sb.AppendLine("using Drizzle4Dotnet.Dialect;");
            sb.AppendLine("using Drizzle4Dotnet.Core.Schema.Tables;");
            sb.AppendLine("using Drizzle4Dotnet.Core.Schema.Columns;");

            if (!string.IsNullOrEmpty(model.Namespace))
            {
                sb.AppendLine($"namespace {model.Namespace};");
            }

            var selectStructProperties = string.Join(", ", model.Properties.Select(p => $"{p.Type} {p.Name}"));
            
            var sqlFragments = string.Join(", ", model.Properties.Select(p => $"{{{p.ColumnSql}.Sql}}"));

            // var selectStructMapper = string.Join(",\n                ", model.Properties.Select((p, i) => 
            //     $"r.IsDBNull({i}) ? default({p.Type}) : r.GetFieldValue<{p.Type}>({i})"));
            // var selectModelMapper = string.Join(",\n                ",
            //     model.Properties.Select((p, i) =>
            //         $"{p.Name} = r.IsDBNull({i}) ? default({p.Type}) : r.GetFieldValue<{p.Type}>({i})"));
            
            var selectStructMapper = string.Join(",\n                ", model.Properties.Select((p, i) => {
                var isNullable = Utils.IsNullable(p.Type);
                var method = Utils.GetDataReaderMethod(p.Type);
                if (!isNullable) {
                    return $"r.Get{method}({i})";
                }
                return $"r.IsDBNull({i}) ? default : r.Get{method}({i})";
            }));
            var selectModelMapper = string.Join(",\n                ",
                model.Properties.Select((p, i) => {
                    var isNullable = Utils.IsNullable(p.Type);
                    var method = Utils.GetDataReaderMethod(p.Type);
                    if (!isNullable) {
                        return $"{p.Name} = r.Get{method}({i})";
                    }
                    return $"{p.Name} = r.IsDBNull({i}) ? default : r.Get{method}({i})";
                }));


            sb.AppendLine($@"
public partial class {model.Name}: ISelection<{
    model.Name
}, {
    model.Name
}.SelectResult, PgSqlSqlDialectImpl, {model.Name}.GeneratedSubqueryTable>
{{
    public readonly record struct SelectResult({selectStructProperties});

    public static ISelectedColumns<SelectResult, PgSqlSqlDialectImpl, {model.Name}.GeneratedSubqueryTable> Record {{ get; }} = new GeneratedStructSelection();
    public static ISelectedColumns<{model.Name}, PgSqlSqlDialectImpl, {model.Name}.GeneratedSubqueryTable> Mapping {{ get; }} = new GeneratedModelSelection();

    public class GeneratedSubqueryTable: IVirtualTable<PgSqlSqlDialectImpl>, ICteTable<PgSqlSqlDialectImpl>
    {{
        private readonly IGenericSql _baseSql;
        private readonly string _aliasName;
        private readonly bool _isCte = false;
        public void BuildSql(ISqlBuilder sqlBuilder) {{
            if (_isCte) {{
                sqlBuilder.Append(PgSqlSqlDialectImpl.BuildIdentifier(_aliasName));
                sqlBuilder.Append("" AS ("");
                _baseSql.BuildSql(sqlBuilder);
                sqlBuilder.Append(')');
                return;
            }}

            sqlBuilder.Append('(');
            _baseSql.BuildSql(sqlBuilder);
            sqlBuilder.Append("") AS "");
            sqlBuilder.Append(PgSqlSqlDialectImpl.BuildIdentifier(_aliasName));
        }}

        public ICteTable<PgSqlSqlDialectImpl> AsCte() {{
            return new GeneratedSubqueryTable(_aliasName, _baseSql, true);
        }}

        public void BuildRefSql(ISqlBuilder sqlBuilder)
        {{
            sqlBuilder.Append(PgSqlSqlDialectImpl.BuildIdentifier(_aliasName));
        }}

        {string.Join("\n        ", model.Properties.Select(p => $"public VirtualColumn<{p.Type}, PgSqlSqlDialectImpl> {p.Name} {{ get; set; }}"))}

        public GeneratedSubqueryTable(
            string aliasName,
            IGenericSql baseSql,
            bool isCte = false
        ) {{
            _baseSql = baseSql;
            _aliasName = aliasName;
            _isCte = isCte;
            {string.Join("\n            ", model.Properties.Select(p => $"this.{p.Name} = new VirtualColumn<{p.Type}, PgSqlSqlDialectImpl>(aliasName, {p.ColumnSql}.Identifier);"))}
        }}

        public static IVirtualTable<PgSqlSqlDialectImpl> Create(IGenericSql baseSql, string aliasName, object _) => new GeneratedSubqueryTable(aliasName, baseSql);
    }}

    private sealed class GeneratedStructSelection : ISelectedColumns<SelectResult, PgSqlSqlDialectImpl, {model.Name}.GeneratedSubqueryTable>
    {{
        public void BuildSql(ISqlBuilder sqlBuilder) => sqlBuilder.Append(_sql);

        private static readonly string _sql;

        static GeneratedStructSelection() {{
            _sql = $""{sqlFragments}"";
        }}

        public SelectResult Mapper(DbDataReader r)
        {{
            return new SelectResult(
                {selectStructMapper}
            );
        }}
    }}

    private sealed class GeneratedModelSelection : ISelectedColumns<{model.Name}, PgSqlSqlDialectImpl, {model.Name}.GeneratedSubqueryTable>
    {{
        public void BuildSql(ISqlBuilder sqlBuilder) => sqlBuilder.Append(_sql);

        private static readonly string _sql;

        static GeneratedModelSelection() {{
            _sql = $""{sqlFragments}"";
        }}

        public {model.Name} Mapper(DbDataReader r)
        {{
            return new {model.Name} 
            {{
                {selectModelMapper}
            }};
        }}
    }}
}}");


            context.AddSource($"{model.Name}_generated.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    static ClassModel? GetClassModel(GeneratorSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;

        if (symbol == null || !symbol.GetAttributes().Any(a => a.AttributeClass?.Name == "DbSelectAttribute"))
            return null;

        var props = new List<PropertyModel>();
        foreach (var member in symbol.GetMembers())
        {
            if (member is IPropertySymbol propSymbol)
            {
                var mapAttr = propSymbol.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.Name == "MapWithAttribute");

                if (mapAttr != null)
                {
                    
                    var colSql = ExtractColumnSql(ctx,
                        mapAttr
                        );
                    if (colSql == null)
                    {
                        continue;
                    }
                    
                    props.Add(new PropertyModel
                    {
                        Name = propSymbol.Name,
                        ColumnSql = colSql,
                        Type = propSymbol.Type.ToDisplayString()
                    });
                }
            }
        }

        return new ClassModel
        {
            Name = symbol.Name,
            Namespace = (symbol.ContainingNamespace == null 
                         || symbol.ContainingNamespace.IsGlobalNamespace
                         || symbol.ContainingNamespace.ToDisplayString() == "<global namespace>"
                         ) 
                        ? "" : symbol.ContainingNamespace.ToDisplayString(),
            Properties = props
        };
    }

    private static string? ExtractColumnSql(
        GeneratorSyntaxContext ctx,
        AttributeData attr
        )
    {
        var attrSyntax = attr.ApplicationSyntaxReference?.GetSyntax() as AttributeSyntax;
        if (attrSyntax?.ArgumentList == null
            || attrSyntax.ArgumentList.Arguments.Count < 2) 
            return null;

        var argTableType = attrSyntax.ArgumentList.Arguments[0];
        if (argTableType.Expression is not TypeOfExpressionSyntax typeOfExpr)
            return null;
        var typeInfo = ctx.SemanticModel.GetTypeInfo(typeOfExpr.Type);
        if (typeInfo.Type is not INamedTypeSymbol tableTypeSymbol)
            return null;
        
        var tableNamespace = (
            tableTypeSymbol.ContainingNamespace == null 
            || tableTypeSymbol.ContainingNamespace.IsGlobalNamespace
            || tableTypeSymbol.ContainingNamespace.ToDisplayString() == "<global namespace>"
            ) ? "" : tableTypeSymbol.ContainingNamespace.ToDisplayString();
        var tableName = tableTypeSymbol.Name;
        
        var argColumnName = attrSyntax?.ArgumentList?.Arguments[1];
        if (argColumnName == null) return null;
        var columnNameExpr = argColumnName.Expression.ToString();
        if (!columnNameExpr.Contains($"{tableName}.ColumnNames."))
            return null;
        return $"{(string.IsNullOrEmpty(tableNamespace) ? "" : $"{tableNamespace}.")}{columnNameExpr.Replace(".ColumnNames", "")}";
    }
}

public class PropertyModel
{
    public string Name { get; set; }
    public string Type { get; set; }
    public string ColumnSql { get; set; }
}

public class ClassModel
{
    public string Name { get; set; }
    public string Namespace { get; set; }
    public List<PropertyModel> Properties { get; set; }
}
