using Drizzle4Dotnet.Core.Shared;

namespace Drizzle4Dotnet.Core.Schema.Migration;

/// <summary>
/// Builds a CREATE TABLE DDL statement from a <see cref="TableDefinition"/>.
/// </summary>
public class CreateTableQuery : ISql
{
    private readonly TableDefinition _table;
    private bool _ifNotExists;
    private bool _temporary;

    public CreateTableQuery(TableDefinition table)
    {
        _table = table;
    }

    /// <summary>
    /// Adds IF NOT EXISTS clause.
    /// </summary>
    public CreateTableQuery IfNotExists()
    {
        _ifNotExists = true;
        return this;
    }

    /// <summary>
    /// Marks the table as TEMPORARY.
    /// </summary>
    public CreateTableQuery Temporary()
    {
        _temporary = true;
        return this;
    }

    public void BuildSql(ISqlBuilder sqlBuilder)
    {
        // CREATE [TEMPORARY] TABLE [IF NOT EXISTS] schema.table (...)
        sqlBuilder.Append("CREATE ");
        if (_temporary)
        {
            sqlBuilder.Append("TEMPORARY ");
        }
        sqlBuilder.Append("TABLE ");
        if (_ifNotExists)
        {
            sqlBuilder.Append("IF NOT EXISTS ");
        }

        var fullTableName = string.IsNullOrEmpty(_table.SchemaName)
            ? _table.TableName
            : $"{_table.SchemaName}.{_table.TableName}";
        sqlBuilder.Append(fullTableName);

        sqlBuilder.Append(" (\n");

        var parts = new List<string>();
        foreach (var col in _table.Columns)
        {
            parts.Add(BuildColumnSql(col));
        }

        // Add table-level constraints
        foreach (var constraint in _table.TableConstraints)
        {
            parts.Add(constraint);
        }

        sqlBuilder.Append(string.Join(",\n", parts));
        sqlBuilder.Append("\n)");
    }

    private static string BuildColumnSql(IColumnDefinition col)
    {
        var sb = new System.Text.StringBuilder();
        sb.Append("  ");
        sb.Append(col.Name);
        sb.Append(' ');
        sb.Append(col.DataType);

        if (col.IsAutoIncrement)
        {
            sb.Append(" GENERATED BY DEFAULT AS IDENTITY");
        }

        if (!col.IsNullable)
        {
            sb.Append(" NOT NULL");
        }

        if (col.DefaultValue != null)
        {
            sb.Append(" DEFAULT ");
            sb.Append(col.DefaultValue);
        }

        if (col.IsPrimaryKey)
        {
            sb.Append(" PRIMARY KEY");
        }

        if (col.CheckExpression != null)
        {
            sb.Append(" CHECK (");
            sb.Append(col.CheckExpression);
            sb.Append(')');
        }

        return sb.ToString();
    }
}

/// <summary>
/// Builds a DROP TABLE DDL statement.
/// </summary>
public class DropTableQuery : ISql
{
    private readonly string _tableName;
    private readonly string _schemaName;
    private bool _ifExists;
    private bool _cascade;

    public DropTableQuery(string tableName, string schemaName = "public")
    {
        _tableName = tableName;
        _schemaName = schemaName;
    }

    /// <summary>
    /// Adds IF EXISTS clause.
    /// </summary>
    public DropTableQuery IfExists()
    {
        _ifExists = true;
        return this;
    }

    /// <summary>
    /// Adds CASCADE clause.
    /// </summary>
    public DropTableQuery Cascade()
    {
        _cascade = true;
        return this;
    }

    public void BuildSql(ISqlBuilder sqlBuilder)
    {
        sqlBuilder.Append("DROP TABLE ");
        if (_ifExists)
        {
            sqlBuilder.Append("IF EXISTS ");
        }

        var fullTableName = string.IsNullOrEmpty(_schemaName)
            ? _tableName
            : $"{_schemaName}.{_tableName}";
        sqlBuilder.Append(fullTableName);

        if (_cascade)
        {
            sqlBuilder.Append(" CASCADE");
        }
    }
}

/// <summary>
/// Builds a CREATE INDEX DDL statement.
/// </summary>
public class CreateIndexQuery : ISql
{
    private readonly string _indexName;
    private readonly string _tableName;
    private readonly string _schemaName;
    private readonly List<string> _columns = new();
    private bool _unique;
    private bool _ifNotExists;
    private string? _indexType; // e.g., "BTREE", "HASH", "GIN", "GiST"
    private string? _where; // Partial index

    public CreateIndexQuery(string indexName, string tableName, string schemaName = "public")
    {
        _indexName = indexName;
        _tableName = tableName;
        _schemaName = schemaName;
    }

    /// <summary>
    /// Specifies the column(s) for the index.
    /// </summary>
    public CreateIndexQuery On(params string[] columns)
    {
        _columns.AddRange(columns);
        return this;
    }

    /// <summary>
    /// Makes the index UNIQUE.
    /// </summary>
    public CreateIndexQuery Unique()
    {
        _unique = true;
        return this;
    }

    /// <summary>
    /// Adds IF NOT EXISTS clause.
    /// </summary>
    public CreateIndexQuery IfNotExists()
    {
        _ifNotExists = true;
        return this;
    }

    /// <summary>
    /// Sets the index type (e.g., "BTREE", "HASH", "GIN", "GiST").
    /// </summary>
    public CreateIndexQuery Using(string indexType)
    {
        _indexType = indexType;
        return this;
    }

    /// <summary>
    /// Adds a partial index WHERE condition.
    /// </summary>
    public CreateIndexQuery Where(string condition)
    {
        _where = condition;
        return this;
    }

    public void BuildSql(ISqlBuilder sqlBuilder)
    {
        sqlBuilder.Append("CREATE ");
        if (_unique)
        {
            sqlBuilder.Append("UNIQUE ");
        }
        sqlBuilder.Append("INDEX ");
        if (_ifNotExists)
        {
            sqlBuilder.Append("IF NOT EXISTS ");
        }
        sqlBuilder.Append(_indexName);
        sqlBuilder.Append(" ON ");

        var fullTableName = string.IsNullOrEmpty(_schemaName)
            ? _tableName
            : $"{_schemaName}.{_tableName}";
        sqlBuilder.Append(fullTableName);

        if (_indexType != null)
        {
            sqlBuilder.Append(" USING ");
            sqlBuilder.Append(_indexType);
        }

        sqlBuilder.Append(" (");
        sqlBuilder.Append(string.Join(", ", _columns));
        sqlBuilder.Append(')');

        if (_where != null)
        {
            sqlBuilder.Append(" WHERE ");
            sqlBuilder.Append(_where);
        }
    }
}

/// <summary>
/// Builds a DROP INDEX DDL statement.
/// </summary>
public class DropIndexQuery : ISql
{
    private readonly string _indexName;
    private readonly string? _tableName; // Needed for PostgreSQL: DROP INDEX IF EXISTS table.index
    private bool _ifExists;
    private bool _cascade;

    public DropIndexQuery(string indexName, string? tableName = null)
    {
        _indexName = indexName;
        _tableName = tableName;
    }

    public DropIndexQuery IfExists()
    {
        _ifExists = true;
        return this;
    }

    public DropIndexQuery Cascade()
    {
        _cascade = true;
        return this;
    }

    public void BuildSql(ISqlBuilder sqlBuilder)
    {
        sqlBuilder.Append("DROP INDEX ");
        if (_ifExists)
        {
            sqlBuilder.Append("IF EXISTS ");
        }

        if (_tableName != null)
        {
            sqlBuilder.Append(_tableName);
            sqlBuilder.Append('.');
        }
        sqlBuilder.Append(_indexName);

        if (_cascade)
        {
            sqlBuilder.Append(" CASCADE");
        }
    }
}

/// <summary>
/// Builds an ALTER TABLE DDL statement for adding, dropping, or modifying columns.
/// </summary>
public class AlterTableQuery : ISql
{
    private readonly string _tableName;
    private readonly string _schemaName;
    private readonly List<AlterTableAction> _actions = new();

    public AlterTableQuery(string tableName, string schemaName = "public")
    {
        _tableName = tableName;
        _schemaName = schemaName;
    }

    /// <summary>
    /// Adds a column to the table.
    /// </summary>
    public AlterTableQuery AddColumn(IColumnDefinition column)
    {
        _actions.Add(new AlterTableAction(AlterTableActionType.AddColumn, column));
        return this;
    }

    /// <summary>
    /// Drops a column from the table.
    /// </summary>
    public AlterTableQuery DropColumn(string columnName)
    {
        _actions.Add(new AlterTableAction(AlterTableActionType.DropColumn, columnName: columnName));
        return this;
    }

    /// <summary>
    /// Alters a column's data type.
    /// </summary>
    public AlterTableQuery AlterColumnType(string columnName, string newDataType, string? usingExpression = null)
    {
        _actions.Add(new AlterTableAction(AlterTableActionType.AlterColumnType, 
            columnName: columnName, newDataType: newDataType, usingExpression: usingExpression));
        return this;
    }

    /// <summary>
    /// Sets a column to NOT NULL.
    /// </summary>
    public AlterTableQuery SetNotNull(string columnName)
    {
        _actions.Add(new AlterTableAction(AlterTableActionType.SetNotNull, columnName: columnName));
        return this;
    }

    /// <summary>
    /// Drops a column's NOT NULL constraint.
    /// </summary>
    public AlterTableQuery DropNotNull(string columnName)
    {
        _actions.Add(new AlterTableAction(AlterTableActionType.DropNotNull, columnName: columnName));
        return this;
    }

    /// <summary>
    /// Sets a default value for a column.
    /// </summary>
    public AlterTableQuery SetDefault(string columnName, string defaultValue)
    {
        _actions.Add(new AlterTableAction(AlterTableActionType.SetDefault, 
            columnName: columnName, newDefault: defaultValue));
        return this;
    }

    /// <summary>
    /// Drops the default value of a column.
    /// </summary>
    public AlterTableQuery DropDefault(string columnName)
    {
        _actions.Add(new AlterTableAction(AlterTableActionType.DropDefault, columnName: columnName));
        return this;
    }

    /// <summary>
    /// Renames a column.
    /// </summary>
    public AlterTableQuery RenameColumn(string oldName, string newName)
    {
        _actions.Add(new AlterTableAction(AlterTableActionType.RenameColumn, 
            columnName: oldName, newName: newName));
        return this;
    }

    /// <summary>
    /// Adds a table constraint (e.g., FOREIGN KEY, UNIQUE).
    /// </summary>
    public AlterTableQuery AddConstraint(string constraintDefinition)
    {
        _actions.Add(new AlterTableAction(AlterTableActionType.AddConstraint, constraintSql: constraintDefinition));
        return this;
    }

    /// <summary>
    /// Drops a constraint by name.
    /// </summary>
    public AlterTableQuery DropConstraint(string constraintName)
    {
        _actions.Add(new AlterTableAction(AlterTableActionType.DropConstraint, columnName: constraintName));
        return this;
    }

    public void BuildSql(ISqlBuilder sqlBuilder)
    {
        var fullTableName = string.IsNullOrEmpty(_schemaName)
            ? _tableName
            : $"{_schemaName}.{_tableName}";

        foreach (var action in _actions)
        {
            sqlBuilder.Append("ALTER TABLE ");
            sqlBuilder.Append(fullTableName);
            sqlBuilder.Append(' ');

            switch (action.ActionType)
            {
                case AlterTableActionType.AddColumn:
                    sqlBuilder.Append("ADD COLUMN ");
                    AppendColumnDef(sqlBuilder, action.Column!);
                    break;

                case AlterTableActionType.DropColumn:
                    sqlBuilder.Append("DROP COLUMN ");
                    sqlBuilder.Append(action.ColumnName);
                    break;

                case AlterTableActionType.AlterColumnType:
                    sqlBuilder.Append("ALTER COLUMN ");
                    sqlBuilder.Append(action.ColumnName);
                    sqlBuilder.Append(" TYPE ");
                    sqlBuilder.Append(action.NewDataType);
                    if (action.UsingExpression != null)
                    {
                        sqlBuilder.Append(" USING ");
                        sqlBuilder.Append(action.UsingExpression);
                    }
                    break;

                case AlterTableActionType.SetNotNull:
                    sqlBuilder.Append("ALTER COLUMN ");
                    sqlBuilder.Append(action.ColumnName);
                    sqlBuilder.Append(" SET NOT NULL");
                    break;

                case AlterTableActionType.DropNotNull:
                    sqlBuilder.Append("ALTER COLUMN ");
                    sqlBuilder.Append(action.ColumnName);
                    sqlBuilder.Append(" DROP NOT NULL");
                    break;

                case AlterTableActionType.SetDefault:
                    sqlBuilder.Append("ALTER COLUMN ");
                    sqlBuilder.Append(action.ColumnName);
                    sqlBuilder.Append(" SET DEFAULT ");
                    sqlBuilder.Append(action.NewDefault);
                    break;

                case AlterTableActionType.DropDefault:
                    sqlBuilder.Append("ALTER COLUMN ");
                    sqlBuilder.Append(action.ColumnName);
                    sqlBuilder.Append(" DROP DEFAULT");
                    break;

                case AlterTableActionType.RenameColumn:
                    sqlBuilder.Append("RENAME COLUMN ");
                    sqlBuilder.Append(action.ColumnName);
                    sqlBuilder.Append(" TO ");
                    sqlBuilder.Append(action.NewName);
                    break;

                case AlterTableActionType.AddConstraint:
                    sqlBuilder.Append("ADD ");
                    sqlBuilder.Append(action.ConstraintSql);
                    break;

                case AlterTableActionType.DropConstraint:
                    sqlBuilder.Append("DROP CONSTRAINT ");
                    sqlBuilder.Append(action.ColumnName);
                    break;
            }

            sqlBuilder.Append(";\n");
        }
    }

    private static void AppendColumnDef(ISqlBuilder sqlBuilder, IColumnDefinition col)
    {
        sqlBuilder.Append(col.Name);
        sqlBuilder.Append(' ');
        sqlBuilder.Append(col.DataType);

        if (col.IsAutoIncrement)
        {
            sqlBuilder.Append(" GENERATED BY DEFAULT AS IDENTITY");
        }

        if (!col.IsNullable)
        {
            sqlBuilder.Append(" NOT NULL");
        }

        if (col.DefaultValue != null)
        {
            sqlBuilder.Append(" DEFAULT ");
            sqlBuilder.Append(col.DefaultValue);
        }

        if (col.IsPrimaryKey)
        {
            sqlBuilder.Append(" PRIMARY KEY");
        }
    }

    private enum AlterTableActionType
    {
        AddColumn,
        DropColumn,
        AlterColumnType,
        SetNotNull,
        DropNotNull,
        SetDefault,
        DropDefault,
        RenameColumn,
        AddConstraint,
        DropConstraint
    }

    private sealed class AlterTableAction
    {
        public AlterTableActionType ActionType { get; }
        public IColumnDefinition? Column { get; }
        public string? ColumnName { get; }
        public string? NewDataType { get; }
        public string? NewDefault { get; }
        public string? NewName { get; }
        public string? UsingExpression { get; }
        public string? ConstraintSql { get; }

        public AlterTableAction(
            AlterTableActionType actionType,
            IColumnDefinition? column = null,
            string? columnName = null,
            string? newDataType = null,
            string? newDefault = null,
            string? newName = null,
            string? usingExpression = null,
            string? constraintSql = null)
        {
            ActionType = actionType;
            Column = column;
            ColumnName = columnName;
            NewDataType = newDataType;
            NewDefault = newDefault;
            NewName = newName;
            UsingExpression = usingExpression;
            ConstraintSql = constraintSql;
        }
    }
}
