using System.Data.Common;
using Drizzle4Dotnet.Core.Shared;

namespace Drizzle4Dotnet.Core.Schema.Migration;

/// <summary>
/// Manages schema migrations against the database.
/// Provides the ability to create, track, and apply migrations.
/// </summary>
public class MigrationManager<TDialect> where TDialect : ISqlDialect
{
    private readonly DbConnection _connection;
    private readonly DbTransaction? _transaction;
    private const string MigrationTableName = "__Migrations";
    private const string MigrationSchemaName = "public";

    /// <summary>
    /// Creates a new MigrationManager for the given connection.
    /// </summary>
    public MigrationManager(DbConnection connection, DbTransaction? transaction = null)
    {
        _connection = connection;
        _transaction = transaction;
    }

    /// <summary>
    /// Ensures the migration history table exists in the database.
    /// </summary>
    public async Task EnsureMigrationTableAsync()
    {
        var createTableSql = $@"
CREATE TABLE IF NOT EXISTS {MigrationSchemaName}.{MigrationTableName} (
    ""Id"" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""Name"" TEXT NOT NULL,
    ""AppliedAt"" TIMESTAMP NOT NULL DEFAULT NOW(),
    ""Checksum"" TEXT NOT NULL
)";

        await using var cmd = _connection.CreateCommand();
        cmd.Transaction = _transaction;
        cmd.CommandText = createTableSql;
        await cmd.ExecuteNonQueryAsync();
    }

    /// <summary>
    /// Gets a list of already applied migrations from the database.
    /// </summary>
    public async Task<List<AppliedMigration>> GetAppliedMigrationsAsync()
    {
        await EnsureMigrationTableAsync();

        var result = new List<AppliedMigration>();
        await using var cmd = _connection.CreateCommand();
        cmd.Transaction = _transaction;
        cmd.CommandText = $@"SELECT ""Name"", ""AppliedAt"", ""Checksum"" FROM {MigrationSchemaName}.{MigrationTableName} ORDER BY ""Id"" ASC";
        await using var reader = await cmd.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            result.Add(new AppliedMigration(
                reader.GetString(0),
                reader.GetDateTime(1),
                reader.GetString(2)
            ));
        }
        return result;
    }

    /// <summary>
    /// Applies a migration plan to the database.
    /// </summary>
    public async Task ApplyMigrationAsync(MigrationPlan plan)
    {
        await using var cmd = _connection.CreateCommand();
        cmd.Transaction = _transaction;

        foreach (var step in plan.Steps)
        {
            var sql = step.ToSql<TDialect>();
            cmd.CommandText = sql;
            await cmd.ExecuteNonQueryAsync();
        }

        // Record the migration
        var checksum = Convert.ToHexString(
            System.Security.Cryptography.SHA256.HashData(
                System.Text.Encoding.UTF8.GetBytes(plan.ToSql<TDialect>())
            )
        );

        cmd.CommandText = $@"
INSERT INTO {MigrationSchemaName}.{MigrationTableName} (""Name"", ""Checksum"")
VALUES (@name, @checksum)";

        var nameParam = cmd.CreateParameter();
        nameParam.ParameterName = "name";
        nameParam.Value = plan.Name;
        cmd.Parameters.Add(nameParam);

        var checksumParam = cmd.CreateParameter();
        checksumParam.ParameterName = "checksum";
        checksumParam.Value = checksum;
        cmd.Parameters.Add(checksumParam);

        await cmd.ExecuteNonQueryAsync();
    }

    /// <summary>
    /// Applies multiple migration plans in order.
    /// </summary>
    public async Task ApplyMigrationsAsync(IEnumerable<MigrationPlan> plans)
    {
        foreach (var plan in plans)
        {
            await ApplyMigrationAsync(plan);
        }
    }

    /// <summary>
    /// Automatically detects schema differences and generates a migration plan.
    /// </summary>
    public MigrationPlan CreateMigrationFromDiff(string migrationName,
        SchemaSnapshot targetSnapshot,
        SchemaSnapshot? currentSnapshot = null)
    {
        if (currentSnapshot == null)
        {
            // If no current snapshot, assume empty schema
            currentSnapshot = new SchemaSnapshot { Name = "current" };
        }

        var diff = currentSnapshot.Compare(targetSnapshot);
        return diff.ToMigrationPlan(migrationName);
    }
}

/// <summary>
/// Represents a previously applied migration.
/// </summary>
public readonly struct AppliedMigration
{
    public string Name { get; }
    public DateTime AppliedAt { get; }
    public string Checksum { get; }

    public AppliedMigration(string name, DateTime appliedAt, string checksum)
    {
        Name = name;
        AppliedAt = appliedAt;
        Checksum = checksum;
    }
}
