using System.Collections.Concurrent;
using System.Reflection;
using Drizzle4Dotnet.Core.Schema.Columns;
using Drizzle4Dotnet.Core.Schema.Migration.Query;
using Drizzle4Dotnet.Core.Schema.Tables;
using Drizzle4Dotnet.Core.Shared;

namespace Drizzle4Dotnet.Core.Schema.Migration;

/// <summary>
/// Extracts <see cref="TableDefinition"/> objects from ORM table schema classes
/// (e.g., <c>UsersTable</c>) via reflection on the source-generated static properties.
/// Works with any dialect (PgSql, MySql, etc.).
/// </summary>
public static class OrmSchemaExporter
{
    /// <summary>
    /// Gets a <see cref="TableDefinition"/> from an ORM table type via reflection.
    /// </summary>
    /// <typeparam name="TTable">The ORM table class (e.g., <c>UsersTable</c>).</typeparam>
    /// <typeparam name="TDialect">The SQL dialect class (e.g., <c>PgSqlDialect</c>).</typeparam>
    public static TableDefinition GetTableDefinition<TTable, TDialect>() where TTable : IDbTable<TDialect> where TDialect : ISqlDialect
    {
        return GetTableDefinition(typeof(TTable), TDialect.ClrToSqlTypeMap);
    }

    /// <summary>
    /// Non-generic entry point for getting a <see cref="TableDefinition"/> from a table type.
    /// Allows calling without knowing the types at compile time, avoiding reflection-based generic method invocation.
    /// </summary>
    /// <param name="tableType">The ORM table class type.</param>
    /// <param name="typeMap">The CLR-to-SQL type mapping dictionary (e.g., from <c>TDialect.ClrToSqlTypeMap</c>).</param>
    public static TableDefinition GetTableDefinition(Type tableType, Dictionary<Type, ISqlDataType> typeMap)
    {
        return ExtractTableDefinition(tableType, typeMap);
    }

    /// <summary>
    /// Gets <see cref="TableDefinition"/> from multiple ORM table types.
    /// </summary>
    public static List<TableDefinition> GetTableDefinitions<TDialect>(params Type[] tableTypes)
        where TDialect : ISqlDialect
    {
        return tableTypes.Select(ExtractTableDefinition<TDialect>).ToList();
    }

    /// <summary>
    /// Creates a <see cref="SchemaSnapshot"/> from multiple table types.
    /// </summary>
    public static SchemaSnapshot CreateSchemaSnapshot<TDialect>(
        string snapshotName, params Type[] tableTypes)
        where TDialect : ISqlDialect
    {
        var defs = tableTypes.Select(ExtractTableDefinition<TDialect>).ToList();
        return SchemaSnapshot.FromTableDefinitions(snapshotName, defs);
    }

    /// <summary>
    /// Convenience method: creates a <see cref="CreateTableQuery"/> from an ORM table type.
    /// </summary>
    public static CreateTableQuery CreateTable<TTable, TDialect>()
        where TTable : IDbTable<TDialect>
        where TDialect : ISqlDialect
    {
        var tableDef = GetTableDefinition<TTable, TDialect>();
        return new CreateTableQuery(tableDef);
    }

    /// <summary>
    /// Extracts a <see cref="TableDefinition"/> from an ORM table type using the provided type map.
    /// Non-generic version that avoids the need for compile-time dialect knowledge.
    /// </summary>
    private static TableDefinition ExtractTableDefinition(Type tableType, Dictionary<Type, ISqlDataType> typeMap)
    {
        // Extract table name from static properties generated by TableGenerator
        var tableName = GetStaticPropertyValue<string>(tableType, "TableName") ?? tableType.Name;
        var schemaName = GetStaticPropertyValue<string>(tableType, "SchemaName") ?? "public";

        // Read typed table-level constraint attributes
        var constraints = new List<TableConstraint>();

        foreach (var fkAttr in tableType.GetCustomAttributes<ForeignKeyConstraintAttribute>())
        {
            var foreignTableName = GetStaticPropertyValue<string>(fkAttr.ForeignTable, "TableName")
                                   ?? fkAttr.ForeignTable.Name;
            constraints.Add(new ForeignKeyConstraint(
                fkAttr.ConstraintName,
                fkAttr.Columns,
                foreignTableName,
                fkAttr.ForeignColumns));
        }

        foreach (var uqAttr in tableType.GetCustomAttributes<UniqueConstraintAttribute>())
        {
            constraints.Add(new UniqueConstraint(uqAttr.Columns));
        }

        foreach (var pkAttr in tableType.GetCustomAttributes<PrimaryKeyTableConstraintAttribute>())
        {
            constraints.Add(new PrimaryKeyTableConstraint(pkAttr.Columns));
        }

        foreach (var ckAttr in tableType.GetCustomAttributes<CheckTableConstraintAttribute>())
        {
            constraints.Add(new CheckTableConstraint(ckAttr.Expression));
        }

        // Read index attributes
        var indexes = new List<TableIndex>();
        foreach (var idxAttr in tableType.GetCustomAttributes<IndexAttribute>())
        {
            indexes.Add(new TableIndex(
                idxAttr.IndexName,
                schemaName,
                tableName,
                idxAttr.Columns,
                isUnique: idxAttr.IsUnique,
                indexType: idxAttr.IndexType,
                where: idxAttr.Where));
        }

        // Extract columns by finding static properties typed as DbColumn<,,> or subclasses
        var columns = new List<IColumnDefinition>();

        foreach (var prop in tableType.GetProperties(BindingFlags.Public | BindingFlags.Static))
        {
            var propType = prop.PropertyType;
            if (!IsColumnType(propType))
                continue;

            var columnName = GetColumnIdentifier(prop);
            if (string.IsNullOrEmpty(columnName))
                continue;

            var clrType = GetColumnClrType(propType);

            // Check for SqlTypeAttribute subclass on the property (e.g., [PgSqlBigInt])
            var sqlTypeAttr = prop.GetCustomAttribute<SqlTypeAttribute>();
            var sqlType = sqlTypeAttr != null ? sqlTypeAttr.ToSqlDataType() : MapClrToSql(clrType, typeMap);

            // Read independent column attributes from the generated static property
            var defaultValueAttr = prop.GetCustomAttribute<DefaultValueAttribute>();
            var autoIncrementAttr = prop.GetCustomAttribute<AutoIncrementAttribute>();
            var notNullAttr = prop.GetCustomAttribute<NotNullAttribute>();
            var nullableAttr = prop.GetCustomAttribute<NullableAttribute>();
            var primaryKeyAttr = prop.GetCustomAttribute<PrimaryKeyAttribute>();
            var checkAttr = prop.GetCustomAttribute<CheckAttribute>();
            var commentAttr = prop.GetCustomAttribute<CommentAttribute>();

            var isNullable = IsClrNullable(clrType);
            if (notNullAttr != null)
                isNullable = false;
            if (nullableAttr != null)
                isNullable = true;

            columns.Add(new ColumnDefinition(columnName, sqlType)
            {
                IsNullable = isNullable,
                IsPrimaryKey = primaryKeyAttr != null,
                IsAutoIncrement = autoIncrementAttr != null,
                DefaultValue = defaultValueAttr?.Value,
                CheckExpression = checkAttr?.Expression,
                Comment = commentAttr?.Comment
            });
        }

        return new TableDefinition(tableName, schemaName, columns, constraints, indexes);
    }

    private static TableDefinition ExtractTableDefinition<TDialect>(Type tableType)
        where TDialect : ISqlDialect
    {
        return ExtractTableDefinition(tableType, TDialect.ClrToSqlTypeMap);
    }

    private static bool IsColumnType(Type type)
    {
        if (type.IsGenericType)
        {
            // Check if it is or inherits from DbColumn<,,>
            var checkType = type;
            while (checkType != null)
            {
                if (checkType.IsGenericType)
                {
                    var genericDef = checkType.GetGenericTypeDefinition();
                    if (genericDef == typeof(DbColumn<,,>))
                        return true;
                }
                checkType = checkType.BaseType;
            }
        }
        return false;
    }

    private static string? GetColumnIdentifier(PropertyInfo prop)
    {
        // Get the static instance of the column
        var instance = prop.GetValue(null);
        if (instance == null)
            return null;

        // DbColumn has an "Identifier" property
        var identifierProp = prop.PropertyType.GetProperty("Identifier",
            BindingFlags.Public | BindingFlags.Instance);
        return identifierProp?.GetValue(instance)?.ToString();
    }

    private static Type GetColumnClrType(Type columnType)
    {
        // Traverse the type hierarchy to find DbColumn<T,,>
        var checkType = columnType;
        while (checkType != null)
        {
            if (checkType.IsGenericType &&
                checkType.GetGenericTypeDefinition() == typeof(DbColumn<,,>))
            {
                return checkType.GetGenericArguments()[0];
            }
            checkType = checkType.BaseType;
        }
        return typeof(string);
    }

    private static ISqlDataType MapClrToSql(Type clrType, Dictionary<Type, ISqlDataType> typeMap)
    {
        // Handle nullable types (Nullable<T>)
        var underlyingType = Nullable.GetUnderlyingType(clrType);
        if (underlyingType != null)
            return MapClrToSql(underlyingType, typeMap);

        // Try exact match
        if (typeMap.TryGetValue(clrType, out var sqlType))
            return sqlType;

        // Try by name for types that might be equivalent
        foreach (var (key, value) in typeMap)
        {
            if (key.IsAssignableFrom(clrType))
                return value;
        }

        return new RawSqlDataType("TEXT");
    }

    private static bool IsClrNullable(Type type)
    {
        if (!type.IsValueType)
            return true; // Reference types (string, etc.) are nullable
        return Nullable.GetUnderlyingType(type) != null;
    }

    private static T? GetStaticPropertyValue<T>(Type type, string propertyName) where T : class
    {
        var prop = type.GetProperty(propertyName, BindingFlags.Public | BindingFlags.Static);
        return prop?.GetValue(null) as T;
    }
}
