using System.Collections.Concurrent;
using System.Reflection;
using Drizzle4Dotnet.Core.Schema.Columns;
using Drizzle4Dotnet.Core.Schema.Migration.Query;
using Drizzle4Dotnet.Core.Schema.Tables;
using Drizzle4Dotnet.Core.Shared;

namespace Drizzle4Dotnet.Core.Schema.Migration;

/// <summary>
/// Extracts <see cref="TableDefinition"/> objects from ORM table schema classes
/// (e.g., <c>UsersTable</c>) via reflection on the source-generated static properties.
/// Works with any dialect (PgSql, MySql, etc.).
/// </summary>
public static class OrmSchemaExporter
{
    private static readonly ConcurrentDictionary<Type, TableDefinition> _cache = new();

    /// <summary>
    /// Gets a <see cref="TableDefinition"/> from an ORM table type via reflection.
    /// </summary>
    /// <typeparam name="TTable">The ORM table class (e.g., <c>UsersTable</c>).</typeparam>
    public static TableDefinition GetTableDefinition<TTable, TDialect>() where TTable : IDbTable<TDialect> where TDialect : ISqlDialect
    {
        var tableDef = ExtractTableDefinition<TDialect>(typeof(TTable));
        return tableDef;
    }

    /// <summary>
    /// Gets <see cref="TableDefinition"/> from multiple ORM table types.
    /// </summary>
    public static List<TableDefinition> GetTableDefinitions<TDialect>(params Type[] tableTypes)
        where TDialect : ISqlDialect
    {
        return tableTypes.Select(t => ExtractTableDefinition<TDialect>(t)).ToList();
    }

    /// <summary>
    /// Creates a <see cref="SchemaSnapshot"/> from multiple table types.
    /// </summary>
    public static SchemaSnapshot CreateSchemaSnapshot<TDialect>(
        string snapshotName, params Type[] tableTypes)
        where TDialect : ISqlDialect
    {
        var defs = tableTypes.Select(t => ExtractTableDefinition<TDialect>(t)).ToList();
        return SchemaSnapshot.FromTableDefinitions(snapshotName, defs);
    }

    /// <summary>
    /// Convenience method: creates a <see cref="CreateTableQuery"/> from an ORM table type.
    /// </summary>
    public static CreateTableQuery CreateTable<TTable, TDialect>()
        where TTable : IDbTable<TDialect>
        where TDialect : ISqlDialect
    {
        var tableDef = GetTableDefinition<TTable, TDialect>();
        return new CreateTableQuery(tableDef);
    }

    private static TableDefinition ExtractTableDefinition<TDialect>(Type tableType)
        where TDialect : ISqlDialect
    {
        var typeMap = TDialect.ClrToSqlTypeMap;
        
        // Extract table name from static properties generated by TableGenerator
        var tableName = GetStaticPropertyValue<string>(tableType, "TableName") ?? tableType.Name;
        var schemaName = GetStaticPropertyValue<string>(tableType, "SchemaName") ?? "public";

        // Extract columns by finding static properties typed as DbColumn<,,> or subclasses
        var columns = new List<IColumnDefinition>();

        foreach (var prop in tableType.GetProperties(BindingFlags.Public | BindingFlags.Static))
        {
            var propType = prop.PropertyType;
            if (!IsColumnType(propType))
                continue;

            var columnName = GetColumnIdentifier(prop);
            if (string.IsNullOrEmpty(columnName))
                continue;

            var clrType = GetColumnClrType(propType);

            // Check for SqlTypeAttribute subclass on the property (e.g., [PgSqlBigInt])
            var sqlTypeAttr = prop.GetCustomAttribute<SqlTypeAttribute>();
            ISqlDataType sqlType;
            if (sqlTypeAttr != null)
            {
                sqlType = sqlTypeAttr.ToSqlDataType();
            }
            else
            {
                sqlType = MapClrToSql(clrType, typeMap);
            }

            var isNullable = IsClrNullable(clrType);

            columns.Add(new ColumnDefinition<TDialect>(columnName, sqlType)
            {
                IsNullable = isNullable
            });
        }

        return new TableDefinition(tableName, schemaName, columns);
    }

    private static bool IsColumnType(Type type)
    {
        if (type.IsGenericType)
        {
            // Check if it is or inherits from DbColumn<,,>
            var checkType = type;
            while (checkType != null)
            {
                if (checkType.IsGenericType)
                {
                    var genericDef = checkType.GetGenericTypeDefinition();
                    if (genericDef == typeof(DbColumn<,,>))
                        return true;
                }
                checkType = checkType.BaseType;
            }
        }
        return false;
    }

    private static string? GetColumnIdentifier(PropertyInfo prop)
    {
        // Get the static instance of the column
        var instance = prop.GetValue(null);
        if (instance == null)
            return null;

        // DbColumn has an "Identifier" property
        var identifierProp = prop.PropertyType.GetProperty("Identifier",
            BindingFlags.Public | BindingFlags.Instance);
        return identifierProp?.GetValue(instance)?.ToString();
    }

    private static Type GetColumnClrType(Type columnType)
    {
        // Traverse the type hierarchy to find DbColumn<T,,>
        var checkType = columnType;
        while (checkType != null)
        {
            if (checkType.IsGenericType &&
                checkType.GetGenericTypeDefinition() == typeof(DbColumn<,,>))
            {
                return checkType.GetGenericArguments()[0];
            }
            checkType = checkType.BaseType;
        }
        return typeof(string);
    }

    private static ISqlDataType MapClrToSql(Type clrType, Dictionary<Type, ISqlDataType> typeMap)
    {
        // Handle nullable types (Nullable<T>)
        var underlyingType = Nullable.GetUnderlyingType(clrType);
        if (underlyingType != null)
            return MapClrToSql(underlyingType, typeMap);

        // Try exact match
        if (typeMap.TryGetValue(clrType, out var sqlType))
            return sqlType;

        // Try by name for types that might be equivalent
        foreach (var (key, value) in typeMap)
        {
            if (key.IsAssignableFrom(clrType))
                return value;
        }

        return new RawSqlDataType("TEXT");
    }

    private static bool IsClrNullable(Type type)
    {
        if (!type.IsValueType)
            return true; // Reference types (string, etc.) are nullable
        return Nullable.GetUnderlyingType(type) != null;
    }

    private static T? GetStaticPropertyValue<T>(Type type, string propertyName) where T : class
    {
        var prop = type.GetProperty(propertyName, BindingFlags.Public | BindingFlags.Static);
        return prop?.GetValue(null) as T;
    }

    /// <summary>
    /// Clears the internal type-to-definition cache.
    /// </summary>
    public static void ClearCache()
    {
        _cache.Clear();
    }
}
