// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Data.Common;
using Drizzle4Dotnet.Core.Default.Query;
using Drizzle4Dotnet.Core.Query.Delete;
using Drizzle4Dotnet.Core.Query.Insert;
using Drizzle4Dotnet.Core.Query.Select;
using Drizzle4Dotnet.Core.Query.Update;
using Drizzle4Dotnet.Core.Schema.Columns;
using Drizzle4Dotnet.Core.Schema.Tables;
using Drizzle4Dotnet.Core.Shared;

namespace Drizzle4Dotnet.Core.Default;

public static class SqlDbClientExtensions
{
    public static DefaultSelectQuery<T1, TypedTupleGeneratedSubqueryTable<T1, DefaultSqlDialectImpl>> Select<T1>(this SqlDbClient builder, IAliasedSql<T1> col1)
        => builder.Select(new TypedTupleSelectedColumns<T1, DefaultSqlDialectImpl>(col1));

    public static DefaultSelectQuery<T1, TypedTupleGeneratedSubqueryTable<T1, DefaultSqlDialectImpl>> SelectDistinct<T1>(this SqlDbClient builder, IAliasedSql<T1> col1)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, DefaultSqlDialectImpl>(col1));

    public static DefaultSelectQuery<(T1, T2), TypedTupleGeneratedSubqueryTable<(T1, T2), DefaultSqlDialectImpl>> Select<T1, T2>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, DefaultSqlDialectImpl>(col1, col2));

    public static DefaultSelectQuery<(T1, T2), TypedTupleGeneratedSubqueryTable<(T1, T2), DefaultSqlDialectImpl>> SelectDistinct<T1, T2>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, DefaultSqlDialectImpl>(col1, col2));

    public static DefaultSelectQuery<(T1, T2, T3), TypedTupleGeneratedSubqueryTable<(T1, T2, T3), DefaultSqlDialectImpl>> Select<T1, T2, T3>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, DefaultSqlDialectImpl>(col1, col2, col3));

    public static DefaultSelectQuery<(T1, T2, T3), TypedTupleGeneratedSubqueryTable<(T1, T2, T3), DefaultSqlDialectImpl>> SelectDistinct<T1, T2, T3>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, DefaultSqlDialectImpl>(col1, col2, col3));

    public static DefaultSelectQuery<(T1, T2, T3, T4), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4), DefaultSqlDialectImpl>> Select<T1, T2, T3, T4>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, DefaultSqlDialectImpl>(col1, col2, col3, col4));

    public static DefaultSelectQuery<(T1, T2, T3, T4), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4), DefaultSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, DefaultSqlDialectImpl>(col1, col2, col3, col4));

    public static DefaultSelectQuery<(T1, T2, T3, T4, T5), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5), DefaultSqlDialectImpl>> Select<T1, T2, T3, T4, T5>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, DefaultSqlDialectImpl>(col1, col2, col3, col4, col5));

    public static DefaultSelectQuery<(T1, T2, T3, T4, T5), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5), DefaultSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, DefaultSqlDialectImpl>(col1, col2, col3, col4, col5));

    public static DefaultSelectQuery<(T1, T2, T3, T4, T5, T6), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6), DefaultSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, DefaultSqlDialectImpl>(col1, col2, col3, col4, col5, col6));

    public static DefaultSelectQuery<(T1, T2, T3, T4, T5, T6), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6), DefaultSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, DefaultSqlDialectImpl>(col1, col2, col3, col4, col5, col6));

    public static DefaultSelectQuery<(T1, T2, T3, T4, T5, T6, T7), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7), DefaultSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, DefaultSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7));

    public static DefaultSelectQuery<(T1, T2, T3, T4, T5, T6, T7), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7), DefaultSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, DefaultSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7));

    public static DefaultSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8), DefaultSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, DefaultSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8));

    public static DefaultSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8), DefaultSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, DefaultSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8));

    public static DefaultSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9), DefaultSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, DefaultSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9));

    public static DefaultSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9), DefaultSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, DefaultSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9));

    public static DefaultSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10), DefaultSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, DefaultSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10));

    public static DefaultSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10), DefaultSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, DefaultSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10));

    public static DefaultSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11), DefaultSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, DefaultSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11));

    public static DefaultSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11), DefaultSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, DefaultSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11));

    public static DefaultSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12), DefaultSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, DefaultSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12));

    public static DefaultSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12), DefaultSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, DefaultSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12));

    public static DefaultSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13), DefaultSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, DefaultSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13));

    public static DefaultSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13), DefaultSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, DefaultSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13));

    public static DefaultSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14), DefaultSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13, IAliasedSql<T14> col14)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, DefaultSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14));

    public static DefaultSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14), DefaultSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13, IAliasedSql<T14> col14)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, DefaultSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14));

    public static DefaultSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15), DefaultSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13, IAliasedSql<T14> col14, IAliasedSql<T15> col15)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, DefaultSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14, col15));

    public static DefaultSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15), DefaultSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13, IAliasedSql<T14> col14, IAliasedSql<T15> col15)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, DefaultSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14, col15));

    public static DefaultSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16), DefaultSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13, IAliasedSql<T14> col14, IAliasedSql<T15> col15, IAliasedSql<T16> col16)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, DefaultSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14, col15, col16));

    public static DefaultSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16), DefaultSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(this SqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13, IAliasedSql<T14> col14, IAliasedSql<T15> col15, IAliasedSql<T16> col16)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, DefaultSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14, col15, col16));
}
