using Drizzle4Dotnet.Core.Shared;

namespace Drizzle4Dotnet.Core.Schema.Migration.Query;

/// <summary>
/// Builds a CREATE TABLE DDL statement from a <see cref="TableDefinition"/>.
/// </summary>
public class CreateTableQuery : ISql
{
    private readonly TableDefinition _table;
    private bool _ifNotExists;
    private bool _temporary;

    public CreateTableQuery(TableDefinition table)
    {
        _table = table;
    }

    /// <summary>
    /// Adds IF NOT EXISTS clause.
    /// </summary>
    public CreateTableQuery IfNotExists()
    {
        _ifNotExists = true;
        return this;
    }

    /// <summary>
    /// Marks the table as TEMPORARY.
    /// </summary>
    public CreateTableQuery Temporary()
    {
        _temporary = true;
        return this;
    }

    public void BuildSql(ISqlBuilder sqlBuilder)
    {
        // CREATE [TEMPORARY] TABLE [IF NOT EXISTS] schema.table (...)
        sqlBuilder.Append("CREATE ");
        if (_temporary)
        {
            sqlBuilder.Append("TEMPORARY ");
        }
        sqlBuilder.Append("TABLE ");
        if (_ifNotExists)
        {
            sqlBuilder.Append("IF NOT EXISTS ");
        }

        var fullTableName = string.IsNullOrEmpty(_table.SchemaName)
            ? _table.TableName
            : $"{_table.SchemaName}.{_table.TableName}";
        sqlBuilder.Append(fullTableName);

        sqlBuilder.Append(" (\n");

        var parts = new List<string>();
        foreach (var col in _table.Columns)
        {
            parts.Add(BuildColumnSql(col));
        }

        // Add table-level constraints
        foreach (var constraint in _table.TableConstraints)
        {
            parts.Add(constraint);
        }

        sqlBuilder.Append(string.Join(",\n", parts));
        sqlBuilder.Append("\n)");
    }

    private static string BuildColumnSql(IColumnDefinition col)
    {
        var sb = new System.Text.StringBuilder();
        sb.Append("  ");
        sb.Append(col.Name);
        sb.Append(' ');
        sb.Append(col.DataType);

        if (col.IsAutoIncrement)
        {
            sb.Append(" GENERATED BY DEFAULT AS IDENTITY");
        }

        if (!col.IsNullable)
        {
            sb.Append(" NOT NULL");
        }

        if (col.DefaultValue != null)
        {
            sb.Append(" DEFAULT ");
            sb.Append(col.DefaultValue);
        }

        if (col.IsPrimaryKey)
        {
            sb.Append(" PRIMARY KEY");
        }

        if (col.CheckExpression != null)
        {
            sb.Append(" CHECK (");
            sb.Append(col.CheckExpression);
            sb.Append(')');
        }

        return sb.ToString();
    }
}
