// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Data.Common;
using Drizzle4Dotnet.Core.Schema.Columns;
using System.Data.Common;
using Drizzle4Dotnet.Core.Query.Delete;
using Drizzle4Dotnet.Core.Query.Insert;
using Drizzle4Dotnet.Core.Query.Select;
using Drizzle4Dotnet.Core.Query.Update;
using Drizzle4Dotnet.Core.Schema.Columns;
using Drizzle4Dotnet.Core.Schema.Tables;
using Drizzle4Dotnet.Core.Shared;
using Drizzle4Dotnet.Dialect;
using Drizzle4Dotnet.MySql;

namespace Drizzle4Dotnet.Core;

public static class MySqlQueryBuilderExtensions
{

    public static MySqlSelectQuery<T1, TypedTupleGeneratedSubqueryTable<T1, MySqlSqlDialectImpl>> Select<T1>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1)
        => builder.Select(new TypedTupleSelectedColumns<T1, MySqlSqlDialectImpl>(col1));

    public static MySqlSelectQuery<T1,  TypedTupleGeneratedSubqueryTable<T1, MySqlSqlDialectImpl>> SelectDistinct<T1>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1) 
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, MySqlSqlDialectImpl>(col1));

    public static MySqlSelectQuery<(T1, T2),  TypedTupleGeneratedSubqueryTable<(T1, T2), MySqlSqlDialectImpl>> Select<T1, T2>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2) 
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, MySqlSqlDialectImpl>(col1, col2));

    public static MySqlSelectQuery<(T1, T2),  TypedTupleGeneratedSubqueryTable<(T1, T2), MySqlSqlDialectImpl>> SelectDistinct<T1, T2>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2) 
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, MySqlSqlDialectImpl>(col1, col2));

    public static MySqlSelectQuery<(T1, T2, T3),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3), MySqlSqlDialectImpl>> Select<T1, T2, T3>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3) 
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, MySqlSqlDialectImpl>(col1, col2, col3));

    public static MySqlSelectQuery<(T1, T2, T3),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3), MySqlSqlDialectImpl>> SelectDistinct<T1, T2, T3>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3) 
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, MySqlSqlDialectImpl>(col1, col2, col3));

    public static MySqlSelectQuery<(T1, T2, T3, T4),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4), MySqlSqlDialectImpl>> Select<T1, T2, T3, T4>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4) 
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, MySqlSqlDialectImpl>(col1, col2, col3, col4));

    public static MySqlSelectQuery<(T1, T2, T3, T4),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4), MySqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4) 
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, MySqlSqlDialectImpl>(col1, col2, col3, col4));

    public static MySqlSelectQuery<(T1, T2, T3, T4, T5),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5), MySqlSqlDialectImpl>> Select<T1, T2, T3, T4, T5>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5) 
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, MySqlSqlDialectImpl>(col1, col2, col3, col4, col5));

    public static MySqlSelectQuery<(T1, T2, T3, T4, T5),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5), MySqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5) 
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, MySqlSqlDialectImpl>(col1, col2, col3, col4, col5));

    public static MySqlSelectQuery<(T1, T2, T3, T4, T5, T6),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6), MySqlSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6) 
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, MySqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6));

    public static MySqlSelectQuery<(T1, T2, T3, T4, T5, T6),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6), MySqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6) 
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, MySqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6));

    public static MySqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7), MySqlSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7) 
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, MySqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7));

    public static MySqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7), MySqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7) 
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, MySqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7));

    public static MySqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8), MySqlSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8) 
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, MySqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8));

    public static MySqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8), MySqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8) 
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, MySqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8));

    public static MySqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9), MySqlSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9) 
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, MySqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9));

    public static MySqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9), MySqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9) 
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, MySqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9));

    public static MySqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10), MySqlSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10) 
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, MySqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10));

    public static MySqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10), MySqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10) 
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, MySqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10));

    public static MySqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11), MySqlSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11) 
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, MySqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11));

    public static MySqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11), MySqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11) 
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, MySqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11));

    public static MySqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12), MySqlSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12) 
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, MySqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12));

    public static MySqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12), MySqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12) 
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, MySqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12));

    public static MySqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13), MySqlSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13) 
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, MySqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13));

    public static MySqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13), MySqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13) 
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, MySqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13));

    public static MySqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14), MySqlSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13, IAliasedSql<T14> col14) 
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, MySqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14));

    public static MySqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14), MySqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13, IAliasedSql<T14> col14) 
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, MySqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14));

    public static MySqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15), MySqlSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13, IAliasedSql<T14> col14, IAliasedSql<T15> col15) 
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, MySqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14, col15));

    public static MySqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15), MySqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13, IAliasedSql<T14> col14, IAliasedSql<T15> col15) 
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, MySqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14, col15));

    public static MySqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16), MySqlSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13, IAliasedSql<T14> col14, IAliasedSql<T15> col15, IAliasedSql<T16> col16) 
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, MySqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14, col15, col16));

    public static MySqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16), MySqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(this MySqlQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13, IAliasedSql<T14> col14, IAliasedSql<T15> col15, IAliasedSql<T16> col16) 
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, MySqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14, col15, col16));
}
