namespace Drizzle4Dotnet.Core.Schema.Columns;

/// <summary>
/// Marks a property as a database column.
/// </summary>
/// <param name="name">The column name in the database.</param>
[AttributeUsage(AttributeTargets.Property)]
public class ColumnAttribute(string name) : Attribute
{
    /// <summary>The column name in the database.</summary>
    public string Name { get; } = name;

    /// <summary>
    /// Explicitly overrides the SQL data type (e.g., "VARCHAR(100)", "NUMERIC(20,4)", "TEXT").
    /// If not specified, the type is inferred from the CLR type based on the dialect.
    /// </summary>
    public string? DataType { get; set; }

    /// <summary>
    /// Default value expression for the column (e.g., "NOW()", "0", "'default'", "true").
    /// This is the raw SQL expression, not a parameterized value.
    /// </summary>
    public string? DefaultValue { get; set; }

    /// <summary>
    /// Whether the column is auto-increment (IDENTITY / GENERATED BY DEFAULT AS IDENTITY).
    /// </summary>
    public bool AutoIncrement { get; set; }

    /// <summary>
    /// Forces the column to be NOT NULL, even if the CLR type is nullable.
    /// </summary>
    public bool NotNull { get; set; }

    /// <summary>
    /// Forces the column to be nullable, even if the CLR type is non-nullable.
    /// Only applies when <see cref="NotNull"/> is not set.
    /// </summary>
    public bool Nullable { get; set; }

    /// <summary>
    /// A CHECK constraint expression for the column (e.g., "value > 0").
    /// </summary>
    public string? Check { get; set; }

    /// <summary>
    /// Column comment/description.
    /// </summary>
    public string? Comment { get; set; }

    /// <summary>
    /// Whether this column is the primary key.
    /// </summary>
    public bool PrimaryKey { get; set; }
}

/// <summary>
/// Marks a property as a primary key column.
/// </summary>
[AttributeUsage(AttributeTargets.Property)]
public class PrimaryKeyAttribute : Attribute { }
