using System;
using Drizzle4Dotnet.Core.Schema.Migration;

namespace Drizzle4Dotnet.Core.Schema.Columns;

/// <summary>
/// Marks a property as a database column.
/// </summary>
/// <param name="name">The column name in the database.</param>
[AttributeUsage(AttributeTargets.Property)]
public class ColumnAttribute(string name) : Attribute
{
    /// <summary>The column name in the database.</summary>
    public string Name { get; } = name;

    /// <summary>
    /// Default value expression for the column (e.g., "NOW()", "0", "'default'", "true").
    /// This is the raw SQL expression, not a parameterized value.
    /// </summary>
    public string? DefaultValue { get; set; }

    /// <summary>
    /// Whether the column is auto-increment (IDENTITY / GENERATED BY DEFAULT AS IDENTITY).
    /// </summary>
    public bool AutoIncrement { get; set; }

    /// <summary>
    /// Forces the column to be NOT NULL, even if the CLR type is nullable.
    /// </summary>
    public bool NotNull { get; set; }

    /// <summary>
    /// Forces the column to be nullable, even if the CLR type is non-nullable.
    /// Only applies when <see cref="NotNull"/> is not set.
    /// </summary>
    public bool Nullable { get; set; }

    /// <summary>
    /// A CHECK constraint expression for the column (e.g., "value > 0").
    /// </summary>
    public string? Check { get; set; }

    /// <summary>
    /// Column comment/description.
    /// </summary>
    public string? Comment { get; set; }

    /// <summary>
    /// Whether this column is the primary key.
    /// </summary>
    public bool PrimaryKey { get; set; }
}

/// <summary>
/// Marks a property as a primary key column.
/// </summary>
[AttributeUsage(AttributeTargets.Property)]
public class PrimaryKeyAttribute : Attribute { }

/// <summary>
/// Specifies a default value expression for the column (e.g., "NOW()", "0", "'default'", "true").
/// This is the raw SQL expression, not a parameterized value.
/// </summary>
[AttributeUsage(AttributeTargets.Property)]
public class DefaultValueAttribute(string value) : Attribute
{
    /// <summary>The default value SQL expression.</summary>
    public string Value { get; } = value;
}

/// <summary>
/// Marks the column as auto-increment (IDENTITY / GENERATED BY DEFAULT AS IDENTITY).
/// </summary>
[AttributeUsage(AttributeTargets.Property)]
public class AutoIncrementAttribute : Attribute { }

/// <summary>
/// Forces the column to be NOT NULL, even if the CLR type is nullable.
/// </summary>
[AttributeUsage(AttributeTargets.Property)]
public class NotNullAttribute : Attribute { }

/// <summary>
/// Forces the column to be nullable, even if the CLR type is non-nullable.
/// Only applies when <see cref="NotNullAttribute"/> is not present.
/// </summary>
[AttributeUsage(AttributeTargets.Property)]
public class NullableAttribute : Attribute { }

/// <summary>
/// A CHECK constraint expression for the column (e.g., "value > 0").
/// </summary>
[AttributeUsage(AttributeTargets.Property)]
public class CheckAttribute(string expression) : Attribute
{
    /// <summary>The CHECK constraint SQL expression.</summary>
    public string Expression { get; } = expression;
}

/// <summary>
/// Column comment/description.
/// </summary>
[AttributeUsage(AttributeTargets.Property)]
public class CommentAttribute(string comment) : Attribute
{
    /// <summary>The column comment/description.</summary>
    public string Comment { get; } = comment;
}

// ============================================================================
// SQL Data Type Attribute Hierarchy
// ============================================================================

/// <summary>
/// Abstract base attribute for dialect-specific SQL data type annotations.
/// Subclass this to create typed attributes for each data type (e.g., <c>PgSqlIntegerAttribute</c>).
/// Place on a property alongside <see cref="ColumnAttribute"/> to specify the exact SQL column type.
/// </summary>
[AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
public abstract class SqlTypeAttribute : Attribute
{
    /// <summary>
    /// The SQL type name string (e.g., "INTEGER", "BIGINT", "VARCHAR(100)").
    /// </summary>
    public abstract string SqlType { get; }

    /// <summary>
    /// Converts this attribute to an <see cref="ISqlDataType"/> instance.
    /// </summary>
    public ISqlDataType ToSqlDataType() => new RawSqlDataType(SqlType);
}
