// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Data.Common;
using Drizzle4Dotnet.Core.Query.Delete;
using Drizzle4Dotnet.Core.Query.Insert;
using Drizzle4Dotnet.Core.Query.Select;
using Drizzle4Dotnet.Core.Query.Update;
using Drizzle4Dotnet.Core.Schema.Columns;
using Drizzle4Dotnet.Core.Schema.Tables;
using Drizzle4Dotnet.Core.Shared;
using Drizzle4Dotnet.Sqlite;
using Drizzle4Dotnet.Sqlite.Query;

namespace Drizzle4Dotnet.Core;

public static class SqliteQueryBuilderExtensions
{
    public static SqliteSelectQuery<T1, TypedTupleGeneratedSubqueryTable<T1, SqliteSqlDialectImpl>> Select<T1>(this SqliteQueryBuilder builder, IAliasedSql<T1> col1)
        => builder.Select(new TypedTupleSelectedColumns<T1, SqliteSqlDialectImpl>(col1));

    public static SqliteSelectQuery<T1,  TypedTupleGeneratedSubqueryTable<T1, SqliteSqlDialectImpl>> SelectDistinct<T1>(this SqliteQueryBuilder builder, IAliasedSql<T1> col1) 
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, SqliteSqlDialectImpl>(col1));

    public static SqliteSelectQuery<(T1, T2),  TypedTupleGeneratedSubqueryTable<(T1, T2), SqliteSqlDialectImpl>> Select<T1, T2>(this SqliteQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2) 
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, SqliteSqlDialectImpl>(col1, col2));

    public static SqliteSelectQuery<(T1, T2),  TypedTupleGeneratedSubqueryTable<(T1, T2), SqliteSqlDialectImpl>> SelectDistinct<T1, T2>(this SqliteQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2) 
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, SqliteSqlDialectImpl>(col1, col2));

    public static SqliteSelectQuery<(T1, T2, T3),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3), SqliteSqlDialectImpl>> Select<T1, T2, T3>(this SqliteQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3) 
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, SqliteSqlDialectImpl>(col1, col2, col3));

    public static SqliteSelectQuery<(T1, T2, T3),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3), SqliteSqlDialectImpl>> SelectDistinct<T1, T2, T3>(this SqliteQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3) 
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, SqliteSqlDialectImpl>(col1, col2, col3));

    public static SqliteSelectQuery<(T1, T2, T3, T4),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4), SqliteSqlDialectImpl>> Select<T1, T2, T3, T4>(this SqliteQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4) 
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, SqliteSqlDialectImpl>(col1, col2, col3, col4));

    public static SqliteSelectQuery<(T1, T2, T3, T4),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4), SqliteSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4>(this SqliteQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4) 
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, SqliteSqlDialectImpl>(col1, col2, col3, col4));

    public static SqliteSelectQuery<(T1, T2, T3, T4, T5),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5), SqliteSqlDialectImpl>> Select<T1, T2, T3, T4, T5>(this SqliteQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5) 
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, SqliteSqlDialectImpl>(col1, col2, col3, col4, col5));

    public static SqliteSelectQuery<(T1, T2, T3, T4, T5),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5), SqliteSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5>(this SqliteQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5) 
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, SqliteSqlDialectImpl>(col1, col2, col3, col4, col5));

    public static SqliteSelectQuery<(T1, T2, T3, T4, T5, T6),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6), SqliteSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6>(this SqliteQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6) 
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, SqliteSqlDialectImpl>(col1, col2, col3, col4, col5, col6));

    public static SqliteSelectQuery<(T1, T2, T3, T4, T5, T6),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6), SqliteSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6>(this SqliteQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6) 
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, SqliteSqlDialectImpl>(col1, col2, col3, col4, col5, col6));

    public static SqliteSelectQuery<(T1, T2, T3, T4, T5, T6, T7),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7), SqliteSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7>(this SqliteQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7) 
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, SqliteSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7));

    public static SqliteSelectQuery<(T1, T2, T3, T4, T5, T6, T7),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7), SqliteSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7>(this SqliteQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7) 
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, SqliteSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7));

    public static SqliteSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8), SqliteSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8>(this SqliteQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8) 
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, SqliteSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8));

    public static SqliteSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8),  TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8), SqliteSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8>(this SqliteQueryBuilder builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8) 
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, SqliteSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8));
}
