// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Data.Common;
using Drizzle4Dotnet.Core.Query.Delete;
using Drizzle4Dotnet.Core.Query.Insert;
using Drizzle4Dotnet.Core.Query.Select;
using Drizzle4Dotnet.Core.Query.Update;
using Drizzle4Dotnet.Core.Schema.Columns;
using Drizzle4Dotnet.Core.Schema.Tables;
using Drizzle4Dotnet.Core.Shared;
using Drizzle4Dotnet.Mssql;
using Drizzle4Dotnet.Mssql.Query;

namespace Drizzle4Dotnet.Core;

/// <summary>
/// Convenience extension methods for MssqlDbClient.
/// These provide overloads for Select/SelectDistinct with typed columns.
/// </summary>
public static class MssqlDbClientExtensions
{
    public static MssqlSelectQuery<T1, TypedTupleGeneratedSubqueryTable<T1, MssqlSqlDialectImpl>> Select<T1>(this MssqlDbClient builder, IAliasedSql<T1> col1)
        => builder.Select(new TypedTupleSelectedColumns<T1, MssqlSqlDialectImpl>(col1));

    public static MssqlSelectQuery<T1, TypedTupleGeneratedSubqueryTable<T1, MssqlSqlDialectImpl>> SelectDistinct<T1>(this MssqlDbClient builder, IAliasedSql<T1> col1)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, MssqlSqlDialectImpl>(col1));

    public static MssqlSelectQuery<(T1, T2), TypedTupleGeneratedSubqueryTable<(T1, T2), MssqlSqlDialectImpl>> Select<T1, T2>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, MssqlSqlDialectImpl>(col1, col2));

    public static MssqlSelectQuery<(T1, T2), TypedTupleGeneratedSubqueryTable<(T1, T2), MssqlSqlDialectImpl>> SelectDistinct<T1, T2>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, MssqlSqlDialectImpl>(col1, col2));

    public static MssqlSelectQuery<(T1, T2, T3), TypedTupleGeneratedSubqueryTable<(T1, T2, T3), MssqlSqlDialectImpl>> Select<T1, T2, T3>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, MssqlSqlDialectImpl>(col1, col2, col3));

    public static MssqlSelectQuery<(T1, T2, T3), TypedTupleGeneratedSubqueryTable<(T1, T2, T3), MssqlSqlDialectImpl>> SelectDistinct<T1, T2, T3>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, MssqlSqlDialectImpl>(col1, col2, col3));

    public static MssqlSelectQuery<(T1, T2, T3, T4), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4), MssqlSqlDialectImpl>> Select<T1, T2, T3, T4>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, MssqlSqlDialectImpl>(col1, col2, col3, col4));

    public static MssqlSelectQuery<(T1, T2, T3, T4), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4), MssqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, MssqlSqlDialectImpl>(col1, col2, col3, col4));

    public static MssqlSelectQuery<(T1, T2, T3, T4, T5), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5), MssqlSqlDialectImpl>> Select<T1, T2, T3, T4, T5>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, MssqlSqlDialectImpl>(col1, col2, col3, col4, col5));

    public static MssqlSelectQuery<(T1, T2, T3, T4, T5), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5), MssqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, MssqlSqlDialectImpl>(col1, col2, col3, col4, col5));

    public static MssqlSelectQuery<(T1, T2, T3, T4, T5, T6), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6), MssqlSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, MssqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6));

    public static MssqlSelectQuery<(T1, T2, T3, T4, T5, T6), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6), MssqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, MssqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6));

    public static MssqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7), MssqlSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, MssqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7));

    public static MssqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7), MssqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, MssqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7));

    public static MssqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8), MssqlSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, MssqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8));

    public static MssqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8), MssqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, MssqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8));

    public static MssqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9), MssqlSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, MssqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9));

    public static MssqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9), MssqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, MssqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9));

    public static MssqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10), MssqlSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, MssqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10));

    public static MssqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10), MssqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, MssqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10));

    public static MssqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11), MssqlSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, MssqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11));

    public static MssqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11), MssqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, MssqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11));

    public static MssqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12), MssqlSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, MssqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12));

    public static MssqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12), MssqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, MssqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12));

    public static MssqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13), MssqlSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, MssqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13));

    public static MssqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13), MssqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, MssqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13));

    public static MssqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14), MssqlSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13, IAliasedSql<T14> col14)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, MssqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14));

    public static MssqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14), MssqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13, IAliasedSql<T14> col14)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, MssqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14));

    public static MssqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15), MssqlSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13, IAliasedSql<T14> col14, IAliasedSql<T15> col15)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, MssqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14, col15));

    public static MssqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15), MssqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13, IAliasedSql<T14> col14, IAliasedSql<T15> col15)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, MssqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14, col15));

    public static MssqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16), MssqlSqlDialectImpl>> Select<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13, IAliasedSql<T14> col14, IAliasedSql<T15> col15, IAliasedSql<T16> col16)
        => builder.Select(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, MssqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14, col15, col16));

    public static MssqlSelectQuery<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16), TypedTupleGeneratedSubqueryTable<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16), MssqlSqlDialectImpl>> SelectDistinct<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(this MssqlDbClient builder, IAliasedSql<T1> col1, IAliasedSql<T2> col2, IAliasedSql<T3> col3, IAliasedSql<T4> col4, IAliasedSql<T5> col5, IAliasedSql<T6> col6, IAliasedSql<T7> col7, IAliasedSql<T8> col8, IAliasedSql<T9> col9, IAliasedSql<T10> col10, IAliasedSql<T11> col11, IAliasedSql<T12> col12, IAliasedSql<T13> col13, IAliasedSql<T14> col14, IAliasedSql<T15> col15, IAliasedSql<T16> col16)
        => builder.SelectDistinct(new TypedTupleSelectedColumns<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, MssqlSqlDialectImpl>(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14, col15, col16));
}
