using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SourceGenerators1;

[Generator]
public class DbSelectGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => GetClassModel(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(classDeclarations.Collect(), GenerateCode);
    }

    private void GenerateCode(SourceProductionContext context, ImmutableArray<ClassModel?> classes)
    {
        if (classes.IsDefaultOrEmpty) return;

        foreach (var model in classes.Distinct())
        {
            if (model == null) continue;
            
            var sb = new StringBuilder();
            
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Data.Common;");
            sb.AppendLine("using Drizzle_Like.Query.Select;");

            if (!string.IsNullOrEmpty(model.Namespace))
            {
                sb.AppendLine($"namespace {model.Namespace};");
            }

            sb.AppendLine($@"
public partial class {model.Name}
{{
    public record struct Result({string.Join(", ", model.Properties.Select(p => $"{p.Type} {p.Name}"))});

    public static ISelectedColumns<Result> SelectClause {{ get; }} = new GeneratedSelection();

    private sealed class GeneratedSelection : ISelectedColumns<Result>
    {{
        public string Sql => $""{string.Join(", ", model.Properties.Select(p => $"{{{p.ColumnSql}.Sql}}"))}"";

        public Result Mapper(DbDataReader r)
        {{
            return new Result(
                {string.Join(",\n                ", model.Properties.Select((p, i) => $"r.GetFieldValue<{p.Type}>({i})"))}
            );
        }}
    }}
}}");

            context.AddSource($"{model.Name}_generated.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    static ClassModel? GetClassModel(GeneratorSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;

        if (symbol == null || !symbol.GetAttributes().Any(a => a.AttributeClass?.Name == "DbSelectAttribute"))
            return null;

        var props = new List<PropertyModel>();
        foreach (var member in symbol.GetMembers())
        {
            if (member is IPropertySymbol propSymbol)
            {
                var mapAttr = propSymbol.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.Name == "MapWithAttribute");

                if (mapAttr != null)
                {
                    
                    var colSql = ExtractColumnSql(ctx,
                        mapAttr
                        );
                    if (colSql == null)
                    {
                        continue;
                    }
                    
                    props.Add(new PropertyModel
                    {
                        Name = propSymbol.Name,
                        ColumnSql = colSql,
                        Type = propSymbol.Type.ToDisplayString()
                    });
                }
            }
        }

        return new ClassModel
        {
            Name = symbol.Name,
            Namespace = (symbol.ContainingNamespace == null 
                         || symbol.ContainingNamespace.IsGlobalNamespace
                         || symbol.ContainingNamespace.ToDisplayString() == "<global namespace>"
                         ) 
                        ? "" : symbol.ContainingNamespace.ToDisplayString(),
            Properties = props
        };
    }

    private static string? ExtractColumnSql(
        GeneratorSyntaxContext ctx,
        AttributeData attr
        )
    {
        var attrSyntax = attr.ApplicationSyntaxReference?.GetSyntax() as AttributeSyntax;
        if (attrSyntax == null) return null;
        if (attrSyntax.ArgumentList == null
            || attrSyntax.ArgumentList.Arguments.Count < 2) return null;

        var argTableType = attrSyntax.ArgumentList.Arguments[0];
        var typeOfExpr = argTableType.Expression as TypeOfExpressionSyntax;
        if (typeOfExpr == null)
            return null;
        var typeInfo = ctx.SemanticModel.GetTypeInfo(typeOfExpr.Type);
        var tableTypeSymbol = typeInfo.Type as INamedTypeSymbol;
        if (tableTypeSymbol == null)
            return null;
        
        var tableNamespace = (
            tableTypeSymbol.ContainingNamespace == null 
            || tableTypeSymbol.ContainingNamespace.IsGlobalNamespace
            || tableTypeSymbol.ContainingNamespace.ToDisplayString() == "<global namespace>"
            ) ? "" : tableTypeSymbol.ContainingNamespace.ToDisplayString();
        var tableName = tableTypeSymbol.Name;
        
        var argColumnName = attrSyntax?.ArgumentList?.Arguments[1];
        if (argColumnName == null) return null;
        var columnNameExpr = argColumnName.Expression.ToString();
        if (!columnNameExpr.Contains($"{tableName}.Columns."))
            return null;
        return $"{(string.IsNullOrEmpty(tableNamespace) ? "" : $"{tableNamespace}.")}{columnNameExpr.Replace(".Columns", "")}";
    }
}

public class PropertyModel
{
    public string Name { get; set; }
    public string Type { get; set; }
    public string ColumnSql { get; set; }
}

public class ClassModel
{
    public string Name { get; set; }
    public string Namespace { get; set; }
    public List<PropertyModel> Properties { get; set; }
}
