using Drizzle4Dotnet.Core.Schema.Migration;
using Drizzle4Dotnet.Core.Schema.Migration.Query;
using Drizzle4Dotnet.Core.Shared;
using Drizzle4Dotnet.MySql;
using Drizzle4Dotnet.PgSql;
using PgSql = SharedDemo.PgSql;
using MySql = SharedDemo.MySql;

namespace Test.Migration;

[TestFixture]
public class PgSqlMigrationTests
{
    /// <summary>
    /// Helper to build SQL from an ISql object using the PgSql dialect.
    /// </summary>
    private static (string Sql, Dictionary<string, object?> Parameters) Build(ISql sql)
    {
        var builder = new SqlBuilder<PgSqlSqlDialectImpl>();
        sql.BuildSql(builder);
        var result = builder.Build();
        return (result.Item1, result.Item2);
    }

    private static void Print(string title, string sql)
    {
        TestContext.Out.WriteLine("===== " + title + " =====");
        TestContext.Out.WriteLine(sql);
        TestContext.Out.WriteLine("");
    }

    // =========================================================================
    // ColumnDefinition
    // =========================================================================

    [Test]
    public void ColumnDefinition_Basic()
    {
        var col = new ColumnDefinition("Id", "BIGINT")
            .PrimaryKey()
            .AutoIncrement();

        Assert.That(col.Name, Is.EqualTo("Id"));
        Assert.That(col.RawDataType, Is.EqualTo("BIGINT"));
        Assert.That(col.IsPrimaryKey, Is.True);
        Assert.That(col.IsAutoIncrement, Is.True);
        Assert.That(col.IsNullable, Is.False);
    }

    [Test]
    public void ColumnDefinition_Nullable()
    {
        var col = new ColumnDefinition("Name", "TEXT")
            .NotNull();

        Assert.That(col.IsNullable, Is.False);
    }

    [Test]
    public void ColumnDefinition_WithDefault()
    {
        var col = new ColumnDefinition("Salary", "NUMERIC(18,2)")
            .WithDefault("0");

        Assert.That(col.DefaultValue, Is.EqualTo("0"));
    }

    // =========================================================================
    // CreateTableQuery
    // =========================================================================

    [Test]
    public void CreateTable_Basic()
    {
        var table = new TableDefinition("Users", "public", new[]
        {
            new ColumnDefinition("Id", "BIGINT").PrimaryKey().AutoIncrement(),
            new ColumnDefinition("Name", "TEXT").NotNull(),
            new ColumnDefinition("Email", "TEXT").NotNull(),
            new ColumnDefinition("Salary", "NUMERIC(18,2)").WithDefault("0"),
            new ColumnDefinition("CreatedAt", "TIMESTAMP").NotNull().WithDefault("NOW()"),
        });

        var query = new CreateTableQuery(table);
        var (sql, _) = Build(query);
        Print("CREATE TABLE basic", sql);

        Assert.That(sql, Does.StartWith("CREATE TABLE"));
        Assert.That(sql, Does.Contain("public.Users"));
        Assert.That(sql, Does.Contain("Id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY"));
        Assert.That(sql, Does.Contain("Name TEXT NOT NULL"));
        Assert.That(sql, Does.Contain("Email TEXT NOT NULL"));
        Assert.That(sql, Does.Contain("Salary NUMERIC(18,2) DEFAULT 0"));
        Assert.That(sql, Does.Contain("CreatedAt TIMESTAMP NOT NULL DEFAULT NOW()"));
    }

    [Test]
    public void CreateTable_IfNotExists()
    {
        var table = new TableDefinition("Users", "public", new[]
        {
            new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
        });

        var query = new CreateTableQuery(table).IfNotExists();
        var (sql, _) = Build(query);
        Print("CREATE TABLE IF NOT EXISTS", sql);

        Assert.That(sql, Does.Contain("CREATE TABLE IF NOT EXISTS"));
    }

    [Test]
    public void CreateTable_Temporary()
    {
        var table = new TableDefinition("TempData", "public", new[]
        {
            new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
        });

        var query = new CreateTableQuery(table).Temporary();
        var (sql, _) = Build(query);
        Print("CREATE TEMPORARY TABLE", sql);

        Assert.That(sql, Does.Contain("CREATE TEMPORARY TABLE"));
    }

    [Test]
    public void CreateTable_WithConstraints()
    {
        var table = new TableDefinition("Users", "public", new[]
        {
            new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
            new ColumnDefinition("Email", "TEXT").NotNull(),
        }, new[]
        {
            new UniqueConstraint(["Email"], "UQ_Users_Email")
        });

        var query = new CreateTableQuery(table);
        var (sql, _) = Build(query);
        Print("CREATE TABLE with constraint", sql);

        Assert.That(sql, Does.Contain("UNIQUE (\"Email\")"));
    }

    [Test]
    public void CreateTable_NoSchema()
    {
        var table = new TableDefinition("Users", "", new[]
        {
            new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
        });

        var query = new CreateTableQuery(table);
        var (sql, _) = Build(query);
        Print("CREATE TABLE no schema", sql);

        Assert.That(sql, Does.Contain("CREATE TABLE Users"));
        Assert.That(sql, Does.Not.Contain("public"));
    }

    // =========================================================================
    // DropTableQuery
    // =========================================================================

    [Test]
    public void DropTable_Basic()
    {
        var query = new DropTableQuery("Users", "public");
        var (sql, _) = Build(query);
        Print("DROP TABLE", sql);

        Assert.That(sql, Is.EqualTo("DROP TABLE public.Users"));
    }

    [Test]
    public void DropTable_IfExists()
    {
        var query = new DropTableQuery("Users", "public").IfExists();
        var (sql, _) = Build(query);
        Print("DROP TABLE IF EXISTS", sql);

        Assert.That(sql, Does.Contain("DROP TABLE IF EXISTS public.Users"));
    }

    [Test]
    public void DropTable_Cascade()
    {
        var query = new DropTableQuery("Users", "public").Cascade();
        var (sql, _) = Build(query);
        Print("DROP TABLE CASCADE", sql);

        Assert.That(sql, Is.EqualTo("DROP TABLE public.Users CASCADE"));
    }

    [Test]
    public void DropTable_IfExistsCascade()
    {
        var query = new DropTableQuery("Users", "public").IfExists().Cascade();
        var (sql, _) = Build(query);
        Print("DROP TABLE IF EXISTS CASCADE", sql);

        Assert.That(sql, Is.EqualTo("DROP TABLE IF EXISTS public.Users CASCADE"));
    }

    // =========================================================================
    // CreateIndexQuery
    // =========================================================================

    [Test]
    public void CreateIndex_Basic()
    {
        var query = new CreateIndexQuery("IX_Users_Email", "Users", "public")
            .On("Email");
        var (sql, _) = Build(query);
        Print("CREATE INDEX basic", sql);

        Assert.That(sql, Is.EqualTo("CREATE INDEX IX_Users_Email ON public.Users (Email)"));
    }

    [Test]
    public void CreateIndex_Unique()
    {
        var query = new CreateIndexQuery("IX_Users_Email", "Users", "public")
            .On("Email")
            .Unique();
        var (sql, _) = Build(query);
        Print("CREATE UNIQUE INDEX", sql);

        Assert.That(sql, Does.Contain("CREATE UNIQUE INDEX IX_Users_Email ON public.Users (Email)"));
    }

    [Test]
    public void CreateIndex_IfNotExists()
    {
        var query = new CreateIndexQuery("IX_Users_Email", "Users", "public")
            .On("Email")
            .IfNotExists();
        var (sql, _) = Build(query);
        Print("CREATE INDEX IF NOT EXISTS", sql);

        Assert.That(sql, Does.Contain("CREATE INDEX IF NOT EXISTS IX_Users_Email"));
    }

    [Test]
    public void CreateIndex_UsingType()
    {
        var query = new CreateIndexQuery("IX_Users_Email", "Users", "public")
            .On("Email")
            .Using("HASH");
        var (sql, _) = Build(query);
        Print("CREATE INDEX USING HASH", sql);

        Assert.That(sql, Does.Contain("USING HASH"));
    }

    [Test]
    public void CreateIndex_MultipleColumns()
    {
        var query = new CreateIndexQuery("IX_Users_Name_Age", "Users", "public")
            .On("Name", "Age");
        var (sql, _) = Build(query);
        Print("CREATE INDEX multi-column", sql);

        Assert.That(sql, Does.Contain("(Name, Age)"));
    }

    [Test]
    public void CreateIndex_Partial()
    {
        var query = new CreateIndexQuery("IX_Users_Active", "Users", "public")
            .On("Name")
            .Where("IsActive = true");
        var (sql, _) = Build(query);
        Print("CREATE INDEX partial", sql);

        Assert.That(sql, Does.Contain("WHERE IsActive = true"));
    }

    [Test]
    public void CreateIndex_UniquePartial()
    {
        var query = new CreateIndexQuery("IX_Users_ActiveEmail", "Users", "public")
            .On("Email")
            .Unique()
            .Where("IsActive = true");
        var (sql, _) = Build(query);
        Print("CREATE UNIQUE INDEX partial", sql);

        Assert.That(sql, Does.Contain("CREATE UNIQUE INDEX IX_Users_ActiveEmail ON public.Users (Email) WHERE IsActive = true"));
    }

    // =========================================================================
    // DropIndexQuery
    // =========================================================================

    [Test]
    public void DropIndex_Basic()
    {
        var query = new DropIndexQuery("IX_Users_Email");
        var (sql, _) = Build(query);
        Print("DROP INDEX", sql);

        Assert.That(sql, Is.EqualTo("DROP INDEX IX_Users_Email"));
    }

    [Test]
    public void DropIndex_IfExists()
    {
        var query = new DropIndexQuery("IX_Users_Email", "public").IfExists();
        var (sql, _) = Build(query);
        Print("DROP INDEX IF EXISTS", sql);

        Assert.That(sql, Is.EqualTo("DROP INDEX IF EXISTS public.IX_Users_Email"));
    }

    // =========================================================================
    // AlterTableQuery
    // =========================================================================

    [Test]
    public void AlterTable_AddColumn()
    {
        var query = new AlterTableQuery("Users", "public")
            .AddColumn(new ColumnDefinition("MiddleName", "TEXT").NotNull());
        var (sql, _) = Build(query);
        Print("ALTER TABLE ADD COLUMN", sql);

        Assert.That(sql, Does.Contain("ALTER TABLE public.Users ADD COLUMN MiddleName TEXT NOT NULL"));
    }

    [Test]
    public void AlterTable_DropColumn()
    {
        var query = new AlterTableQuery("Users", "public")
            .DropColumn("MiddleName");
        var (sql, _) = Build(query);
        Print("ALTER TABLE DROP COLUMN", sql);

        Assert.That(sql, Does.Contain("ALTER TABLE public.Users DROP COLUMN MiddleName"));
    }

    [Test]
    public void AlterTable_AlterColumnType()
    {
        var query = new AlterTableQuery("Users", "public")
            .AlterColumnType("Salary", "NUMERIC(20,4)");
        var (sql, _) = Build(query);
        Print("ALTER COLUMN TYPE", sql);

        Assert.That(sql, Does.Contain("ALTER TABLE public.Users ALTER COLUMN Salary TYPE NUMERIC(20,4)"));
    }

    [Test]
    public void AlterTable_AlterColumnTypeWithUsing()
    {
        var query = new AlterTableQuery("Users", "public")
            .AlterColumnType("Status", "INTEGER", "Status::integer");
        var (sql, _) = Build(query);
        Print("ALTER COLUMN TYPE USING", sql);

        Assert.That(sql, Does.Contain("ALTER TABLE public.Users ALTER COLUMN Status TYPE INTEGER USING Status::integer"));
    }

    [Test]
    public void AlterTable_SetNotNull()
    {
        var query = new AlterTableQuery("Users", "public")
            .SetNotNull("Email");
        var (sql, _) = Build(query);
        Print("ALTER COLUMN SET NOT NULL", sql);

        Assert.That(sql, Does.Contain("ALTER TABLE public.Users ALTER COLUMN Email SET NOT NULL"));
    }

    [Test]
    public void AlterTable_DropNotNull()
    {
        var query = new AlterTableQuery("Users", "public")
            .DropNotNull("Email");
        var (sql, _) = Build(query);
        Print("ALTER COLUMN DROP NOT NULL", sql);

        Assert.That(sql, Does.Contain("ALTER TABLE public.Users ALTER COLUMN Email DROP NOT NULL"));
    }

    [Test]
    public void AlterTable_SetDefault()
    {
        var query = new AlterTableQuery("Users", "public")
            .SetDefault("CreatedAt", "NOW()");
        var (sql, _) = Build(query);
        Print("ALTER COLUMN SET DEFAULT", sql);

        Assert.That(sql, Does.Contain("ALTER TABLE public.Users ALTER COLUMN CreatedAt SET DEFAULT NOW()"));
    }

    [Test]
    public void AlterTable_DropDefault()
    {
        var query = new AlterTableQuery("Users", "public")
            .DropDefault("CreatedAt");
        var (sql, _) = Build(query);
        Print("ALTER COLUMN DROP DEFAULT", sql);

        Assert.That(sql, Does.Contain("ALTER TABLE public.Users ALTER COLUMN CreatedAt DROP DEFAULT"));
    }

    [Test]
    public void AlterTable_RenameColumn()
    {
        var query = new AlterTableQuery("Users", "public")
            .RenameColumn("Name", "FullName");
        var (sql, _) = Build(query);
        Print("RENAME COLUMN", sql);

        Assert.That(sql, Does.Contain("ALTER TABLE public.Users RENAME COLUMN Name TO FullName"));
    }

    [Test]
    public void AlterTable_AddConstraint()
    {
        var query = new AlterTableQuery("Users", "public")
            .AddConstraint("CONSTRAINT FK_Users_Department FOREIGN KEY (DepartmentId) REFERENCES Departments(Id)");
        var (sql, _) = Build(query);
        Print("ALTER TABLE ADD CONSTRAINT", sql);

        Assert.That(sql, Does.Contain("ALTER TABLE public.Users ADD CONSTRAINT FK_Users_Department FOREIGN KEY (DepartmentId) REFERENCES Departments(Id)"));
    }

    [Test]
    public void AlterTable_DropConstraint()
    {
        var query = new AlterTableQuery("Users", "public")
            .DropConstraint("FK_Users_Department");
        var (sql, _) = Build(query);
        Print("ALTER TABLE DROP CONSTRAINT", sql);

        Assert.That(sql, Does.Contain("ALTER TABLE public.Users DROP CONSTRAINT FK_Users_Department"));
    }

    [Test]
    public void AlterTable_MultipleActions()
    {
        var query = new AlterTableQuery("Users", "public")
            .AddColumn(new ColumnDefinition("MiddleName", "TEXT"))
            .AlterColumnType("Salary", "NUMERIC(20,4)")
            .SetNotNull("Email");
        var (sql, _) = Build(query);
        Print("ALTER TABLE multiple actions", sql);

        // Should have 3 separate ALTER TABLE statements
        var lines = sql.Split(';', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries);
        Assert.That(lines.Length, Is.EqualTo(3));
        Assert.That(lines[0], Does.Contain("ADD COLUMN MiddleName"));
        Assert.That(lines[1], Does.Contain("ALTER COLUMN Salary TYPE NUMERIC(20,4)"));
        Assert.That(lines[2], Does.Contain("ALTER COLUMN Email SET NOT NULL"));
    }

    // =========================================================================
    // SchemaSnapshot
    // =========================================================================

    [Test]
    public void SchemaSnapshot_SerializeDeserialize()
    {
        var table1 = new TableDefinition("Users", "public", new[]
        {
            new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
            new ColumnDefinition("Name", "TEXT").NotNull(),
        });

        var table2 = new TableDefinition("Departments", "public", new[]
        {
            new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
            new ColumnDefinition("Name", "TEXT").NotNull(),
        });

        var snapshot = SchemaSnapshot.FromTableDefinitions("v1", new[] { table1, table2 });
        var json = snapshot.Serialize();
        Print("Snapshot JSON", json);

        Assert.That(json, Does.Contain("v1"));
        Assert.That(json, Does.Contain("Users"));
        Assert.That(json, Does.Contain("Departments"));
        Assert.That(json, Does.Contain("Id"));
        Assert.That(json, Does.Contain("Name"));

        // Deserialize and verify
        var deserialized = SchemaSnapshot.Deserialize(json);
        Assert.That(deserialized.Name, Is.EqualTo("v1"));
        Assert.That(deserialized.Tables.Count, Is.EqualTo(2));
        Assert.That(deserialized.Tables[0].TableName, Is.EqualTo("Users"));
        Assert.That(deserialized.Tables[0].Columns.Count, Is.EqualTo(2));
    }

    [Test]
    public void SchemaSnapshot_Compare_NoChanges()
    {
        var table = new TableDefinition("Users", "public", new[]
        {
            new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
            new ColumnDefinition("Name", "TEXT").NotNull(),
        });

        var snapshot1 = SchemaSnapshot.FromTableDefinitions("v1", new[] { table });
        var snapshot2 = SchemaSnapshot.FromTableDefinitions("v2", new[] { table });

        var diff = snapshot1.Compare(snapshot2);
        Assert.That(diff.HasChanges, Is.False);
        Assert.That(diff.TableChanges.Count, Is.EqualTo(0));
    }

    [Test]
    public void SchemaSnapshot_Compare_AddedTable()
    {
        var snapshot1 = SchemaSnapshot.FromTableDefinitions("v1", Array.Empty<TableDefinition>());
        var snapshot2 = SchemaSnapshot.FromTableDefinitions("v2", new[]
        {
            new TableDefinition("Users", "public", new[]
            {
                new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
            })
        });

        var diff = snapshot1.Compare(snapshot2);
        Assert.That(diff.HasChanges, Is.True);
        Assert.That(diff.TableChanges.Count, Is.EqualTo(1));
        Assert.That(diff.TableChanges[0].ChangeType, Is.EqualTo(TableChangeType.Added));
        Assert.That(diff.TableChanges[0].TableName, Is.EqualTo("Users"));
    }

    [Test]
    public void SchemaSnapshot_Compare_RemovedTable()
    {
        var snapshot1 = SchemaSnapshot.FromTableDefinitions("v1", new[]
        {
            new TableDefinition("Users", "public", new[]
            {
                new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
            })
        });
        var snapshot2 = SchemaSnapshot.FromTableDefinitions("v2", Array.Empty<TableDefinition>());

        var diff = snapshot1.Compare(snapshot2);
        Assert.That(diff.HasChanges, Is.True);
        Assert.That(diff.TableChanges.Count, Is.EqualTo(1));
        Assert.That(diff.TableChanges[0].ChangeType, Is.EqualTo(TableChangeType.Removed));
        Assert.That(diff.TableChanges[0].TableName, Is.EqualTo("Users"));
    }

    [Test]
    public void SchemaSnapshot_Compare_AddedColumn()
    {
        var snapshot1 = SchemaSnapshot.FromTableDefinitions("v1", new[]
        {
            new TableDefinition("Users", "public", new[]
            {
                new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
            })
        });
        var snapshot2 = SchemaSnapshot.FromTableDefinitions("v2", new[]
        {
            new TableDefinition("Users", "public", new[]
            {
                new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
                new ColumnDefinition("Name", "TEXT").NotNull(),
            })
        });

        var diff = snapshot1.Compare(snapshot2);
        Assert.That(diff.HasChanges, Is.True);
        Assert.That(diff.TableChanges.Count, Is.EqualTo(1));
        Assert.That(diff.TableChanges[0].ChangeType, Is.EqualTo(TableChangeType.Modified));
        Assert.That(diff.TableChanges[0].ColumnChanges.Count, Is.EqualTo(1));
        Assert.That(diff.TableChanges[0].ColumnChanges[0].ChangeType, Is.EqualTo(ColumnChangeType.Added));
        Assert.That(diff.TableChanges[0].ColumnChanges[0].ColumnName, Is.EqualTo("Name"));
    }

    [Test]
    public void SchemaSnapshot_Compare_RemovedColumn()
    {
        var snapshot1 = SchemaSnapshot.FromTableDefinitions("v1", new[]
        {
            new TableDefinition("Users", "public", new[]
            {
                new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
                new ColumnDefinition("Name", "TEXT"),
            })
        });
        var snapshot2 = SchemaSnapshot.FromTableDefinitions("v2", new[]
        {
            new TableDefinition("Users", "public", new[]
            {
                new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
            })
        });

        var diff = snapshot1.Compare(snapshot2);
        Assert.That(diff.HasChanges, Is.True);
        Assert.That(diff.TableChanges[0].ColumnChanges[0].ChangeType, Is.EqualTo(ColumnChangeType.Removed));
        Assert.That(diff.TableChanges[0].ColumnChanges[0].ColumnName, Is.EqualTo("Name"));
    }

    [Test]
    public void SchemaSnapshot_Compare_TypeChanged()
    {
        var snapshot1 = SchemaSnapshot.FromTableDefinitions("v1", new[]
        {
            new TableDefinition("Users", "public", new[]
            {
                new ColumnDefinition("Id", "BIGINT"),
                new ColumnDefinition("Salary", "NUMERIC(18,2)"),
            })
        });
        var snapshot2 = SchemaSnapshot.FromTableDefinitions("v2", new[]
        {
            new TableDefinition("Users", "public", new[]
            {
                new ColumnDefinition("Id", "BIGINT"),
                new ColumnDefinition("Salary", "NUMERIC(20,4)"),
            })
        });

        var diff = snapshot1.Compare(snapshot2);
        Assert.That(diff.HasChanges, Is.True);
        Assert.That(diff.TableChanges[0].ColumnChanges[0].ChangeType, Is.EqualTo(ColumnChangeType.TypeChanged));
        Assert.That(diff.TableChanges[0].ColumnChanges[0].ColumnName, Is.EqualTo("Salary"));
    }

    // =========================================================================
    // SchemaDiff → MigrationPlan
    // =========================================================================

    [Test]
    public void SchemaDiff_ToMigrationPlan_AddTable()
    {
        var snapshot1 = SchemaSnapshot.FromTableDefinitions("v1", Array.Empty<TableDefinition>());
        var snapshot2 = SchemaSnapshot.FromTableDefinitions("v2", new[]
        {
            new TableDefinition("Users", "public", new[]
            {
                new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
                new ColumnDefinition("Name", "TEXT").NotNull(),
            })
        });

        var diff = snapshot1.Compare(snapshot2);
        var plan = diff.ToMigrationPlan("AddUsersTable");
        var sql = plan.ToSql<PgSqlSqlDialectImpl>();
        Print("Migration plan - add table", sql);

        Assert.That(plan.Name, Is.EqualTo("AddUsersTable"));
        Assert.That(plan.Steps.Count, Is.EqualTo(1));
        Assert.That(plan.Steps[0].StepType, Is.EqualTo(MigrationStepType.CreateTable));
        Assert.That(sql, Does.Contain("CREATE TABLE"));
        Assert.That(sql, Does.Contain("public.Users"));
        Assert.That(sql, Does.Contain("-- Migration: AddUsersTable"));
    }

    [Test]
    public void SchemaDiff_ToMigrationPlan_DropTable()
    {
        var snapshot1 = SchemaSnapshot.FromTableDefinitions("v1", new[]
        {
            new TableDefinition("Users", "public", new[]
            {
                new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
            })
        });
        var snapshot2 = SchemaSnapshot.FromTableDefinitions("v2", Array.Empty<TableDefinition>());

        var diff = snapshot1.Compare(snapshot2);
        var plan = diff.ToMigrationPlan("DropUsersTable");
        var sql = plan.ToSql<PgSqlSqlDialectImpl>();
        Print("Migration plan - drop table", sql);

        Assert.That(plan.Steps.Count, Is.EqualTo(1));
        Assert.That(plan.Steps[0].StepType, Is.EqualTo(MigrationStepType.DropTable));
        Assert.That(sql, Does.Contain("DROP TABLE public.Users"));
    }

    [Test]
    public void SchemaDiff_ToMigrationPlan_AlterTable()
    {
        var snapshot1 = SchemaSnapshot.FromTableDefinitions("v1", new[]
        {
            new TableDefinition("Users", "public", new[]
            {
                new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
                new ColumnDefinition("Name", "TEXT").NotNull(),
            })
        });
        var snapshot2 = SchemaSnapshot.FromTableDefinitions("v2", new[]
        {
            new TableDefinition("Users", "public", new[]
            {
                new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
                new ColumnDefinition("Name", "VARCHAR(200)").NotNull(),
                new ColumnDefinition("Email", "TEXT").NotNull(),
            })
        });

        var diff = snapshot1.Compare(snapshot2);
        var plan = diff.ToMigrationPlan("AlterUsersTable");
        var sql = plan.ToSql<PgSqlSqlDialectImpl>();
        Print("Migration plan - alter table", sql);

        Assert.That(plan.Steps.Count, Is.EqualTo(1));
        Assert.That(plan.Steps[0].StepType, Is.EqualTo(MigrationStepType.AlterTable));
        Assert.That(sql, Does.Contain("ALTER TABLE public.Users"));
        Assert.That(sql, Does.Contain("ALTER COLUMN Name TYPE VARCHAR(200)"));
        Assert.That(sql, Does.Contain("ADD COLUMN Email TEXT NOT NULL"));
    }

    [Test]
    public void MigrationPlan_EmptyDiff()
    {
        var table = new TableDefinition("Users", "public", new[]
        {
            new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
        });

        var snapshot1 = SchemaSnapshot.FromTableDefinitions("v1", new[] { table });
        var snapshot2 = SchemaSnapshot.FromTableDefinitions("v2", new[] { table });

        var diff = snapshot1.Compare(snapshot2);
        var plan = diff.ToMigrationPlan("NoChanges");
        var sql = plan.ToSql<PgSqlSqlDialectImpl>();

        Assert.That(plan.Steps.Count, Is.EqualTo(0));
        Assert.That(sql, Does.Contain("-- Migration: NoChanges"));
    }

    // =========================================================================
    // OrmSchemaExporter — Extract TableDefinition from ORM table classes
    // =========================================================================

    [Test]
    public void OrmSchemaExporter_ExportUsersTable()
    {
        var tableDef = OrmSchemaExporter.GetTableDefinition<PgSql.UsersTable, PgSqlSqlDialectImpl>();
        Assert.That(tableDef, Is.Not.Null);
        Assert.That(tableDef.TableName, Is.EqualTo("Users"));
        Assert.That(tableDef.SchemaName, Is.EqualTo("public"));
        Assert.That(tableDef.Columns.Count, Is.GreaterThan(0));
    }

    [Test]
    public void OrmSchemaExporter_ExportUsersTable_VerifyColumns()
    {
        var tableDef = OrmSchemaExporter.GetTableDefinition<PgSql.UsersTable, PgSqlSqlDialectImpl>();

        var columnNames = tableDef.Columns.Select(c => c.Name).ToList();
        Assert.That(columnNames, Does.Contain("Id"));
        Assert.That(columnNames, Does.Contain("Name"));
        Assert.That(columnNames, Does.Contain("Email"));
        Assert.That(columnNames, Does.Contain("Age"));
        Assert.That(columnNames, Does.Contain("Salary"));
        Assert.That(columnNames, Does.Contain("IsActive"));
        Assert.That(columnNames, Does.Contain("DepartmentId"));
        Assert.That(columnNames, Does.Contain("RoleId"));
        Assert.That(columnNames, Does.Contain("CreatedAt"));
    }

    [Test]
    public void OrmSchemaExporter_ColumnTypes_PgSql()
    {
        var tableDef = OrmSchemaExporter.GetTableDefinition<PgSql.UsersTable, PgSqlSqlDialectImpl>();

        var idCol = tableDef.Columns.First(c => c.Name == "Id");
        Assert.That(idCol.RawDataType, Is.EqualTo("BIGINT"));

        var nameCol = tableDef.Columns.First(c => c.Name == "Name");
        Assert.That(nameCol.RawDataType, Is.EqualTo("TEXT"));

        var salaryCol = tableDef.Columns.First(c => c.Name == "Salary");
        Assert.That(salaryCol.RawDataType, Is.EqualTo("NUMERIC(18,2)"));

        var isActiveCol = tableDef.Columns.First(c => c.Name == "IsActive");
        Assert.That(isActiveCol.RawDataType, Is.EqualTo("BOOLEAN"));

        var createdAtCol = tableDef.Columns.First(c => c.Name == "CreatedAt");
        Assert.That(createdAtCol.RawDataType, Is.EqualTo("TIMESTAMP"));
    }

    [Test]
    public void OrmSchemaExporter_ColumnTypes_MySql()
    {
        var tableDef = OrmSchemaExporter.GetTableDefinition<MySql.UsersTable, MySqlSqlDialectImpl>();

        var idCol = tableDef.Columns.First(c => c.Name == "Id");
        Assert.That(idCol.RawDataType, Is.EqualTo("BIGINT"));

        var nameCol = tableDef.Columns.First(c => c.Name == "Name");
        Assert.That(nameCol.RawDataType, Is.EqualTo("VARCHAR(255)"));

        var isActiveCol = tableDef.Columns.First(c => c.Name == "IsActive");
        Assert.That(isActiveCol.RawDataType, Is.EqualTo("TINYINT(1)"));
    }

    [Test]
    public void OrmSchemaExporter_NullableDetection()
    {
        var tableDef = OrmSchemaExporter.GetTableDefinition<PgSql.UsersTable, PgSqlSqlDialectImpl>();

        var managerIdCol = tableDef.Columns.FirstOrDefault(c => c.Name == "ManagerId");
        Assert.That(managerIdCol, Is.Not.Null);
        Assert.That(managerIdCol.IsNullable, Is.True);

        var nameCol = tableDef.Columns.First(c => c.Name == "Name");
        Assert.That(nameCol.IsNullable, Is.True);

        var idCol = tableDef.Columns.First(c => c.Name == "Id");
        Assert.That(idCol.IsNullable, Is.False);
    }

    [Test]
    public void OrmSchemaExporter_ExportMultipleTables()
    {
        var tables = OrmSchemaExporter.GetTableDefinitions<PgSqlSqlDialectImpl>(
            typeof(PgSql.UsersTable),
            typeof(PgSql.DepartmentsTable),
            typeof(PgSql.RolesTable)
        );

        Assert.That(tables.Count, Is.EqualTo(3));
        Assert.That(tables[0].TableName, Is.EqualTo("Users"));
        Assert.That(tables[1].TableName, Is.EqualTo("Departments"));
        Assert.That(tables[2].TableName, Is.EqualTo("Roles"));
    }

    [Test]
    public void OrmSchemaExporter_CreateTableFromOrm()
    {
        var createTable = OrmSchemaExporter.CreateTable<PgSql.UsersTable, PgSqlSqlDialectImpl>();
        var (sql, _) = Build(createTable);
        Print("CREATE TABLE from ORM schema", sql);

        Assert.That(sql, Does.StartWith("CREATE TABLE"));
        Assert.That(sql, Does.Contain("public.Users"));
        Assert.That(sql, Does.Contain("Id BIGINT"));
        Assert.That(sql, Does.Contain("Name TEXT"));
        Assert.That(sql, Does.Contain("Email TEXT"));
    }

    [Test]
    public void OrmSchemaExporter_SchemaSnapshotFromOrm()
    {
        var snapshot = OrmSchemaExporter.CreateSchemaSnapshot<PgSqlSqlDialectImpl>("v1",
            typeof(PgSql.UsersTable), typeof(PgSql.DepartmentsTable));

        Assert.That(snapshot.Name, Is.EqualTo("v1"));
        Assert.That(snapshot.Tables.Count, Is.EqualTo(2));
        Assert.That(snapshot.Tables[0].TableName, Is.EqualTo("Users"));
        Assert.That(snapshot.Tables[1].TableName, Is.EqualTo("Departments"));

        var json = snapshot.Serialize();
        var deserialized = SchemaSnapshot.Deserialize(json);
        Assert.That(deserialized.Tables.Count, Is.EqualTo(2));
    }

    [Test]
    public void OrmSchemaExporter_CompareOrmToSnapshot()
    {
        var current = OrmSchemaExporter.CreateSchemaSnapshot<PgSqlSqlDialectImpl>("current", typeof(PgSql.UsersTable));

        var targetColumns = current.Tables[0].Columns.ToList();
        targetColumns.Add(new SnapshotColumn
        {
            Name = "Phone",
            RawDataType = "TEXT",
            IsNullable = true
        });
        var target = new SchemaSnapshot
        {
            Name = "target",
            Tables = new List<SnapshotTable>
            {
                new SnapshotTable
                {
                    SchemaName = current.Tables[0].SchemaName,
                    TableName = current.Tables[0].TableName,
                    Columns = targetColumns
                }
            }
        };

        var diff = current.Compare(target);
        Assert.That(diff.HasChanges, Is.True);
        Assert.That(diff.TableChanges[0].ColumnChanges[0].ChangeType, Is.EqualTo(ColumnChangeType.Added));
        Assert.That(diff.TableChanges[0].ColumnChanges[0].ColumnName, Is.EqualTo("Phone"));

        var plan = diff.ToMigrationPlan("AddPhoneColumn");
        var sql = plan.ToSql<PgSqlSqlDialectImpl>();
        Print("Migration plan from ORM diff", sql);

        Assert.That(sql, Does.Contain("ALTER TABLE public.Users"));
        Assert.That(sql, Does.Contain("ADD COLUMN Phone TEXT"));
    }

    [Test]
    public void OrmSchemaExporter_FullWorkflow()
    {
        var currentSnapshot = OrmSchemaExporter.CreateSchemaSnapshot<PgSqlSqlDialectImpl>("v1",
            typeof(PgSql.UsersTable), typeof(PgSql.DepartmentsTable));

        var targetSnapshot = OrmSchemaExporter.CreateSchemaSnapshot<PgSqlSqlDialectImpl>("v2",
            typeof(PgSql.UsersTable), typeof(PgSql.DepartmentsTable), typeof(PgSql.RolesTable));

        var diff = currentSnapshot.Compare(targetSnapshot);
        var plan = diff.ToMigrationPlan("AddRolesTable");
        var sql = plan.ToSql<PgSqlSqlDialectImpl>();
        Print("Full workflow migration", sql);

        Assert.That(plan.Steps.Count, Is.EqualTo(1));
        Assert.That(plan.Steps[0].StepType, Is.EqualTo(MigrationStepType.CreateTable));
        Assert.That(sql, Does.Contain("CREATE TABLE"));
        Assert.That(sql, Does.Contain("public.Roles"));
    }

    // =========================================================================
    // Full Migration Scenario
    // =========================================================================

    [Test]
    public void Migration_FullScenario()
    {
        // Simulate a full migration from empty schema to v2
        var empty = SchemaSnapshot.FromTableDefinitions("empty", Array.Empty<TableDefinition>());

        var v1 = SchemaSnapshot.FromTableDefinitions("v1", new[]
        {
            new TableDefinition("Users", "public", new[]
            {
                new ColumnDefinition("Id", "BIGINT").PrimaryKey().AutoIncrement(),
                new ColumnDefinition("Name", "TEXT").NotNull(),
                new ColumnDefinition("Email", "TEXT").NotNull(),
                new ColumnDefinition("CreatedAt", "TIMESTAMP").NotNull().WithDefault("NOW()"),
            }),
            new TableDefinition("Departments", "public", new[]
            {
                new ColumnDefinition("Id", "BIGINT").PrimaryKey().AutoIncrement(),
                new ColumnDefinition("Name", "TEXT").NotNull(),
            })
        });

        // v1 → v2: Add Projects table, add Salary column to Users
        var v2 = SchemaSnapshot.FromTableDefinitions("v2", new[]
        {
            new TableDefinition("Users", "public", new[]
            {
                new ColumnDefinition("Id", "BIGINT").PrimaryKey().AutoIncrement(),
                new ColumnDefinition("Name", "TEXT").NotNull(),
                new ColumnDefinition("Email", "TEXT").NotNull(),
                new ColumnDefinition("Salary", "NUMERIC(18,2)").WithDefault("0"),
                new ColumnDefinition("CreatedAt", "TIMESTAMP").NotNull().WithDefault("NOW()"),
            }),
            new TableDefinition("Departments", "public", new[]
            {
                new ColumnDefinition("Id", "BIGINT").PrimaryKey().AutoIncrement(),
                new ColumnDefinition("Name", "TEXT").NotNull(),
            }),
            new TableDefinition("Projects", "public", new[]
            {
                new ColumnDefinition("Id", "BIGINT").PrimaryKey().AutoIncrement(),
                new ColumnDefinition("Name", "TEXT").NotNull(),
                new ColumnDefinition("DepartmentId", "BIGINT").NotNull(),
            })
        });

        // Migration 1: empty → v1
        var diff1 = empty.Compare(v1);
        var plan1 = diff1.ToMigrationPlan("InitialCreate");
        var sql1 = plan1.ToSql<PgSqlSqlDialectImpl>();
        Print("Migration 1: Initial create", sql1);

        Assert.That(plan1.Steps.Count, Is.EqualTo(2));
        Assert.That(plan1.Steps[0].StepType, Is.EqualTo(MigrationStepType.CreateTable));
        Assert.That(plan1.Steps[0].Description, Does.Contain("Users"));
        Assert.That(plan1.Steps[1].StepType, Is.EqualTo(MigrationStepType.CreateTable));
        Assert.That(plan1.Steps[1].Description, Does.Contain("Departments"));

        // Migration 2: v1 → v2
        var diff2 = v1.Compare(v2);
        var plan2 = diff2.ToMigrationPlan("AddProjectsAndSalary");
        var sql2 = plan2.ToSql<PgSqlSqlDialectImpl>();
        Print("Migration 2: Add projects and salary", sql2);

        Assert.That(plan2.Steps.Count, Is.EqualTo(2));

        // First step: alter Users to add Salary column
        Assert.That(plan2.Steps[0].StepType, Is.EqualTo(MigrationStepType.AlterTable));
        Assert.That(plan2.Steps[0].Description, Does.Contain("Users"));
        Assert.That(sql2, Does.Contain("ADD COLUMN Salary NUMERIC(18,2) DEFAULT 0"));

        // Second step: add Projects table
        Assert.That(plan2.Steps[1].StepType, Is.EqualTo(MigrationStepType.CreateTable));
        Assert.That(plan2.Steps[1].Description, Does.Contain("Projects"));
    }

    // =========================================================================
    // TableDefinitionComparer — Direct TableDefinition-to-TableDefinition diff
    // =========================================================================

    [Test]
    public void TableComparer_NewTable_CreateTable()
    {
        var newTable = new TableDefinition("Users", "public", new[]
        {
            new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
            new ColumnDefinition("Name", "TEXT").NotNull(),
        });

        var result = TableDefinitionComparer.Compare(null, newTable);
        Assert.That(result.HasChanges, Is.True);
        Assert.That(result.Statements.Count, Is.EqualTo(1));
        Assert.That(result.Statements[0], Is.TypeOf<CreateTableQuery>());
    }

    [Test]
    public void TableComparer_NoChanges()
    {
        var table = new TableDefinition("Users", "public", new[]
        {
            new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
            new ColumnDefinition("Name", "TEXT").NotNull(),
        });

        var result = TableDefinitionComparer.Compare(table, table);
        Assert.That(result.HasChanges, Is.False);
        Assert.That(result.Statements.Count, Is.EqualTo(0));
    }

    [Test]
    public void TableComparer_AddColumn()
    {
        var oldTable = new TableDefinition("Users", "public", new[]
        {
            new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
        });

        var newTable = new TableDefinition("Users", "public", new[]
        {
            new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
            new ColumnDefinition("Name", "TEXT").NotNull(),
        });

        var result = TableDefinitionComparer.Compare(oldTable, newTable);
        Assert.That(result.HasChanges, Is.True);
        Assert.That(result.Statements.Count, Is.EqualTo(1));
        Assert.That(result.Statements[0], Is.TypeOf<AlterTableQuery>());

        var sql = result.ToSql<PgSqlSqlDialectImpl>();
        Print("Comparer - add column", sql);
        Assert.That(sql, Does.Contain("ADD COLUMN Name TEXT NOT NULL"));
    }

    [Test]
    public void TableComparer_DropColumn()
    {
        var oldTable = new TableDefinition("Users", "public", new[]
        {
            new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
            new ColumnDefinition("Name", "TEXT"),
        });

        var newTable = new TableDefinition("Users", "public", new[]
        {
            new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
        });

        var result = TableDefinitionComparer.Compare(oldTable, newTable);
        Assert.That(result.HasChanges, Is.True);
        Assert.That(result.Statements.Count, Is.EqualTo(1));
        Assert.That(result.Statements[0], Is.TypeOf<AlterTableQuery>());

        var sql = result.ToSql<PgSqlSqlDialectImpl>();
        Print("Comparer - drop column", sql);
        Assert.That(sql, Does.Contain("DROP COLUMN Name"));
    }

    [Test]
    public void TableComparer_AlterColumnType()
    {
        var oldTable = new TableDefinition("Users", "public", new[]
        {
            new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
            new ColumnDefinition("Salary", "INTEGER"),
        });

        var newTable = new TableDefinition("Users", "public", new[]
        {
            new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
            new ColumnDefinition("Salary", "NUMERIC(18,2)"),
        });

        var result = TableDefinitionComparer.Compare(oldTable, newTable);
        Assert.That(result.HasChanges, Is.True);

        var sql = result.ToSql<PgSqlSqlDialectImpl>();
        Print("Comparer - alter column type", sql);
        Assert.That(sql, Does.Contain("ALTER COLUMN Salary TYPE NUMERIC(18,2)"));
    }

    [Test]
    public void TableComparer_SetNotNull()
    {
        var oldTable = new TableDefinition("Users", "public", new[]
        {
            new ColumnDefinition("Name", "TEXT") { IsNullable = true },
        });

        var newTable = new TableDefinition("Users", "public", new[]
        {
            new ColumnDefinition("Name", "TEXT") { IsNullable = false },
        });

        var result = TableDefinitionComparer.Compare(oldTable, newTable);
        Assert.That(result.HasChanges, Is.True);

        var sql = result.ToSql<PgSqlSqlDialectImpl>();
        Print("Comparer - set not null", sql);
        Assert.That(sql, Does.Contain("ALTER COLUMN Name SET NOT NULL"));
    }

    [Test]
    public void TableComparer_DropNotNull()
    {
        var oldTable = new TableDefinition("Users", "public", new[]
        {
            new ColumnDefinition("Name", "TEXT") { IsNullable = false },
        });

        var newTable = new TableDefinition("Users", "public", new[]
        {
            new ColumnDefinition("Name", "TEXT") { IsNullable = true },
        });

        var result = TableDefinitionComparer.Compare(oldTable, newTable);
        Assert.That(result.HasChanges, Is.True);

        var sql = result.ToSql<PgSqlSqlDialectImpl>();
        Print("Comparer - drop not null", sql);
        Assert.That(sql, Does.Contain("ALTER COLUMN Name DROP NOT NULL"));
    }

    [Test]
    public void TableComparer_ChangeDefault()
    {
        var oldTable = new TableDefinition("Users", "public", new[]
        {
            new ColumnDefinition("Salary", "NUMERIC(18,2)").WithDefault("0"),
        });

        var newTable = new TableDefinition("Users", "public", new[]
        {
            new ColumnDefinition("Salary", "NUMERIC(18,2)").WithDefault("100"),
        });

        var result = TableDefinitionComparer.Compare(oldTable, newTable);
        Assert.That(result.HasChanges, Is.True);

        var sql = result.ToSql<PgSqlSqlDialectImpl>();
        Print("Comparer - change default", sql);
        Assert.That(sql, Does.Contain("SET DEFAULT 100"));
    }

    [Test]
    public void TableComparer_DropDefault()
    {
        var oldTable = new TableDefinition("Users", "public", new[]
        {
            new ColumnDefinition("Salary", "NUMERIC(18,2)").WithDefault("0"),
        });

        var newTable = new TableDefinition("Users", "public", new[]
        {
            new ColumnDefinition("Salary", "NUMERIC(18,2)"),
        });

        var result = TableDefinitionComparer.Compare(oldTable, newTable);
        Assert.That(result.HasChanges, Is.True);

        var sql = result.ToSql<PgSqlSqlDialectImpl>();
        Print("Comparer - drop default", sql);
        Assert.That(sql, Does.Contain("DROP DEFAULT"));
    }

    [Test]
    public void TableComparer_MultipleChanges()
    {
        var oldTable = new TableDefinition("Users", "public", new[]
        {
            new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
            new ColumnDefinition("Name", "TEXT").NotNull(),
            new ColumnDefinition("Salary", "INTEGER").WithDefault("0"),
        });

        var newTable = new TableDefinition("Users", "public", new[]
        {
            new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
            new ColumnDefinition("Name", "VARCHAR(200)").NotNull(),
            new ColumnDefinition("Salary", "NUMERIC(18,2)").WithDefault("0"),
            new ColumnDefinition("Email", "TEXT").NotNull(),
        });

        var result = TableDefinitionComparer.Compare(oldTable, newTable);
        Assert.That(result.HasChanges, Is.True);
        Assert.That(result.Statements.Count, Is.EqualTo(1));
        Assert.That(result.Changes.Count, Is.GreaterThanOrEqualTo(2));

        var sql = result.ToSql<PgSqlSqlDialectImpl>();
        Print("Comparer - multiple changes", sql);
        Assert.That(sql, Does.Contain("ALTER COLUMN Name TYPE VARCHAR(200)"));
        Assert.That(sql, Does.Contain("ALTER COLUMN Salary TYPE NUMERIC(18,2)"));
        Assert.That(sql, Does.Contain("ADD COLUMN Email TEXT NOT NULL"));
    }

    [Test]
    public void TableComparer_CompareSets()
    {
        var oldTables = new Dictionary<(string, string), TableDefinition>
        {
            { ("public", "Users"), new TableDefinition("Users", "public", new[]
                {
                    new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
                })
            },
            { ("public", "Departments"), new TableDefinition("Departments", "public", new[]
                {
                    new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
                })
            },
        };

        var newTables = new Dictionary<(string, string), TableDefinition>
        {
            { ("public", "Users"), new TableDefinition("Users", "public", new[]
                {
                    new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
                    new ColumnDefinition("Name", "TEXT").NotNull(),
                })
            },
            { ("public", "Roles"), new TableDefinition("Roles", "public", new[]
                {
                    new ColumnDefinition("Id", "BIGINT").PrimaryKey(),
                })
            },
        };

        var result = TableDefinitionComparer.CompareSets(oldTables, newTables);
        Assert.That(result.HasChanges, Is.True);

        var sql = result.ToSql<PgSqlSqlDialectImpl>();
        Print("Comparer - compare sets", sql);
        Assert.That(sql, Does.Contain("ADD COLUMN Name TEXT NOT NULL"));  // Users modified
        Assert.That(sql, Does.Contain("CREATE TABLE public.Roles"));     // Roles added
        Assert.That(sql, Does.Contain("DROP TABLE public.Departments")); // Departments removed
    }

    // =========================================================================
    // SharedDemo Schema Verification — validates source-generated SchemaDefinition
    // =========================================================================

    [Test]
    public void SharedDemo_PgSql_UsersTable_Schema()
    {
        var schema = PgSql.UsersTable.SchemaDefinition;
        Assert.That(schema.TableName, Is.EqualTo("Users"));
        Assert.That(schema.SchemaName, Is.EqualTo("public"));

        var cols = schema.Columns.ToDictionary(c => c.Name);
        Assert.That(cols["Id"].RawDataType, Is.EqualTo("BIGINT"));
        Assert.That(cols["Id"].IsPrimaryKey, Is.True);
        Assert.That(cols["Id"].IsNullable, Is.False);

        Assert.That(cols["Guid"].RawDataType, Is.EqualTo("UUID"));
        Assert.That(cols["Guid"].IsNullable, Is.False);

        Assert.That(cols["Name"].RawDataType, Is.EqualTo("TEXT"));
        Assert.That(cols["Name"].IsNullable, Is.False);

        Assert.That(cols["Salary"].RawDataType, Is.EqualTo("NUMERIC(18,2)"));
        Assert.That(cols["Salary"].DefaultValue, Is.EqualTo("0"));

        Assert.That(cols["CreatedAt"].RawDataType, Is.EqualTo("TIMESTAMP"));
        Assert.That(cols["CreatedAt"].DefaultValue, Is.EqualTo("NOW()"));
        Assert.That(cols["CreatedAt"].IsNullable, Is.False);

        Assert.That(cols["ManagerId"].RawDataType, Is.EqualTo("BIGINT"));
        Assert.That(cols["ManagerId"].IsNullable, Is.True);

        // Verify CREATE TABLE SQL output
        var sql = PgSql.UsersTable.ToCreateTableSqlPgSql();
        Print("PgSql Users DDL", sql);
        Assert.That(sql, Does.Contain("CREATE TABLE public.Users"));
        Assert.That(sql, Does.Contain("Id BIGINT NOT NULL PRIMARY KEY"));
        Assert.That(sql, Does.Contain("Salary NUMERIC(18,2) NOT NULL DEFAULT 0"));
        Assert.That(sql, Does.Contain("CreatedAt TIMESTAMP NOT NULL DEFAULT NOW()"));
        Assert.That(sql, Does.Contain("ManagerId BIGINT"));
    }

    [Test]
    public void SharedDemo_PgSql_DepartmentsTable_Schema()
    {
        var schema = PgSql.DepartmentsTable.SchemaDefinition;
        Assert.That(schema.TableName, Is.EqualTo("Departments"));

        var cols = schema.Columns.ToDictionary(c => c.Name);
        Assert.That(cols["Id"].RawDataType, Is.EqualTo("BIGINT"));
        Assert.That(cols["Id"].IsPrimaryKey, Is.True);

        Assert.That(cols["Name"].RawDataType, Is.EqualTo("TEXT"));
        Assert.That(cols["Name"].IsNullable, Is.False);

        Assert.That(cols["Budget"].RawDataType, Is.EqualTo("NUMERIC(18,2)"));
        Assert.That(cols["Budget"].DefaultValue, Is.EqualTo("0"));

        Assert.That(cols["Description"].RawDataType, Is.EqualTo("TEXT"));

        var sql = PgSql.DepartmentsTable.ToCreateTableSqlPgSql();
        Print("PgSql Departments DDL", sql);
        Assert.That(sql, Does.Contain("CREATE TABLE public.Departments"));
    }

    [Test]
    public void SharedDemo_PgSql_RolesTable_Schema()
    {
        var schema = PgSql.RolesTable.SchemaDefinition;
        Assert.That(schema.TableName, Is.EqualTo("Roles"));

        var cols = schema.Columns.ToDictionary(c => c.Name);
        Assert.That(cols["Id"].RawDataType, Is.EqualTo("BIGINT"));
        Assert.That(cols["Id"].IsPrimaryKey, Is.True);

        Assert.That(cols["BaseSalary"].RawDataType, Is.EqualTo("NUMERIC(18,2)"));
        Assert.That(cols["BonusRate"].RawDataType, Is.EqualTo("DOUBLE PRECISION"));

        Assert.That(cols["CanApproveBudget"].RawDataType, Is.EqualTo("BOOLEAN"));

        var sql = PgSql.RolesTable.ToCreateTableSqlPgSql();
        Print("PgSql Roles DDL", sql);
        Assert.That(sql, Does.Contain("CREATE TABLE public.Roles"));
    }

    [Test]
    public void SharedDemo_PgSql_ProjectsTable_Schema()
    {
        var schema = PgSql.ProjectsTable.SchemaDefinition;
        Assert.That(schema.TableName, Is.EqualTo("Projects"));

        var cols = schema.Columns.ToDictionary(c => c.Name);
        Assert.That(cols["Code"].RawDataType, Is.EqualTo("TEXT"));
        Assert.That(cols["OwnerId"].RawDataType, Is.EqualTo("BIGINT"));
        Assert.That(cols["Progress"].RawDataType, Is.EqualTo("DOUBLE PRECISION"));
        Assert.That(cols["StartDate"].RawDataType, Is.EqualTo("TIMESTAMP"));
        Assert.That(cols["StartDate"].IsNullable, Is.False);

        var sql = PgSql.ProjectsTable.ToCreateTableSqlPgSql();
        Print("PgSql Projects DDL", sql);
        Assert.That(sql, Does.Contain("CREATE TABLE public.Projects"));
    }

    [Test]
    public void SharedDemo_PgSql_UserProjectsTable_Schema()
    {
        var schema = PgSql.UserProjectsTable.SchemaDefinition;
        Assert.That(schema.TableName, Is.EqualTo("UserProjects"));

        var cols = schema.Columns.ToDictionary(c => c.Name);
        Assert.That(cols["UserId"].RawDataType, Is.EqualTo("BIGINT"));
        Assert.That(cols["ProjectId"].RawDataType, Is.EqualTo("BIGINT"));
        Assert.That(cols["Role"].RawDataType, Is.EqualTo("TEXT"));
        Assert.That(cols["Allocation"].RawDataType, Is.EqualTo("DOUBLE PRECISION"));
        Assert.That(cols["HourlyRate"].RawDataType, Is.EqualTo("NUMERIC(18,2)"));
        Assert.That(cols["AssignedAt"].RawDataType, Is.EqualTo("TIMESTAMP"));

        var sql = PgSql.UserProjectsTable.ToCreateTableSqlPgSql();
        Print("PgSql UserProjects DDL", sql);
        Assert.That(sql, Does.Contain("CREATE TABLE public.UserProjects"));
    }

    [Test]
    public void SharedDemo_MySql_UsersTable_Schema()
    {
        var schema = SharedDemo.MySql.UsersTable.SchemaDefinition;
        Assert.That(schema.TableName, Is.EqualTo("Users"));

        var cols = schema.Columns.ToDictionary(c => c.Name);
        Assert.That(cols["Id"].RawDataType, Is.EqualTo("BIGINT"));
        Assert.That(cols["Id"].IsPrimaryKey, Is.True);
        Assert.That(cols["Id"].IsAutoIncrement, Is.True);

        Assert.That(cols["Guid"].RawDataType, Is.EqualTo("CHAR(36)"));
        Assert.That(cols["Name"].RawDataType, Is.EqualTo("VARCHAR(255)"));
        Assert.That(cols["Email"].RawDataType, Is.EqualTo("VARCHAR(255)"));
        Assert.That(cols["IsActive"].RawDataType, Is.EqualTo("TINYINT(1)"));
        Assert.That(cols["Salary"].RawDataType, Is.EqualTo("DECIMAL(18,2)"));
        Assert.That(cols["Rating"].RawDataType, Is.EqualTo("DOUBLE"));
        Assert.That(cols["CreatedAt"].RawDataType, Is.EqualTo("DATETIME(6)"));
        Assert.That(cols["DeletedAt"].RawDataType, Is.EqualTo("DATETIME(6)"));
        Assert.That(cols["DeletedAt"].IsNullable, Is.True);

        var sql = SharedDemo.MySql.UsersTable.ToCreateTableSqlMySql();
        Print("MySql Users DDL", sql);
        Assert.That(sql, Does.Contain("CREATE TABLE"));
        Assert.That(sql, Does.Contain("Id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY"));
        Assert.That(sql, Does.Contain("Name VARCHAR(255) NOT NULL"));
        Assert.That(sql, Does.Contain("IsActive TINYINT(1) NOT NULL"));
    }

    [Test]
    public void SharedDemo_MySql_ProjectsTable_Schema()
    {
        var schema = SharedDemo.MySql.ProjectsTable.SchemaDefinition;
        Assert.That(schema.TableName, Is.EqualTo("Projects"));

        var cols = schema.Columns.ToDictionary(c => c.Name);
        Assert.That(cols["Code"].RawDataType, Is.EqualTo("VARCHAR(100)"));
        Assert.That(cols["StartDate"].RawDataType, Is.EqualTo("DATETIME(6)"));

        var sql = SharedDemo.MySql.ProjectsTable.ToCreateTableSqlMySql();
        Print("MySql Projects DDL", sql);
        Assert.That(sql, Does.Contain("CREATE TABLE"));
    }

    [Test]
    public void SharedDemo_PgSql_ToCreateTableSql_MatchesExpectedOutput()
    {
        var sql = PgSql.UsersTable.ToCreateTableSqlPgSql();
        Print("PgSql Users CREATE TABLE", sql);

        // Verify the generated SQL matches the expected schema
        Assert.That(sql, Does.StartWith("CREATE TABLE public.Users"));
        Assert.That(sql, Does.Contain("Id BIGINT"));
        Assert.That(sql, Does.Contain("Guid UUID"));
        Assert.That(sql, Does.Contain("Name TEXT"));
        Assert.That(sql, Does.Contain("Email TEXT"));
        Assert.That(sql, Does.Contain("Salary NUMERIC(18,2) NOT NULL DEFAULT 0"));
        Assert.That(sql, Does.Contain("CreatedAt TIMESTAMP NOT NULL DEFAULT NOW()"));
        Assert.That(sql, Does.Contain("ManagerId BIGINT"));

        // Verify order: PRIMARY KEY should be on Id
        Assert.That(sql, Does.Contain("Id BIGINT NOT NULL PRIMARY KEY"));
    }

    [Test]
    public void SharedDemo_AllTables_HaveSchemaDefinitions()
    {
        Assert.That(PgSql.UsersTable.SchemaDefinition, Is.Not.Null);
        Assert.That(PgSql.DepartmentsTable.SchemaDefinition, Is.Not.Null);
        Assert.That(PgSql.RolesTable.SchemaDefinition, Is.Not.Null);
        Assert.That(PgSql.ProjectsTable.SchemaDefinition, Is.Not.Null);
        Assert.That(PgSql.UserProjectsTable.SchemaDefinition, Is.Not.Null);
        Assert.That(MySql.UsersTable.SchemaDefinition, Is.Not.Null);
        Assert.That(MySql.DepartmentsTable.SchemaDefinition, Is.Not.Null);
        Assert.That(MySql.RolesTable.SchemaDefinition, Is.Not.Null);
        Assert.That(MySql.ProjectsTable.SchemaDefinition, Is.Not.Null);
        Assert.That(MySql.UserProjectsTable.SchemaDefinition, Is.Not.Null);
    }
}
